/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Ai: () => import('#controllers/ai_controller'),
  Billing: () => import('#controllers/billing_controller'),
  BoatEngineParts: () => import('#controllers/boat_engine_parts_controller'),
  BoatEquipment: () => import('#controllers/boat_equipment_controller'),
  BoatMaintenanceSheetItems: () => import('#controllers/boat_maintenance_sheet_items_controller'),
  BoatMaintenanceSheets: () => import('#controllers/boat_maintenance_sheets_controller'),
  BoatMaintenanceTasks: () => import('#controllers/boat_maintenance_tasks_controller'),
  BoatMaintenances: () => import('#controllers/boat_maintenances_controller'),
  BoatMedia: () => import('#controllers/boat_media_controller'),
  BoatSafetyEquipment: () => import('#controllers/boat_safety_equipment_controller'),
  BoatSimulator: () => import('#controllers/boat_simulator_controller'),
  Boats: () => import('#controllers/boats_controller'),
  Home: () => import('#controllers/home_controller'),
  MaintenanceHistory: () => import('#controllers/maintenance_history_controller'),
  Marketing: () => import('#controllers/marketing_controller'),
  Mouillages: () => import('#controllers/mouillages_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  OrganizationInvitations: () => import('#controllers/organization_invitations_controller'),
  OrganizationMembers: () => import('#controllers/organization_members_controller'),
  PasswordReset: () => import('#controllers/password_reset_controller'),
  Planning: () => import('#controllers/planning_controller'),
  Pontoons: () => import('#controllers/pontoons_controller'),
  Ports: () => import('#controllers/ports_controller'),
  Session: () => import('#controllers/session_controller'),
  Settings: () => import('#controllers/settings_controller'),
  Simulator: () => import('#controllers/simulator_controller'),
  SimulatorLead: () => import('#controllers/simulator_lead_controller'),
  Spots: () => import('#controllers/spots_controller'),
  dev: {
    MailPreviews: () => import('#controllers/dev/mail_previews_controller'),
  },
}
