/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Ai: () => import('#controllers/ai_controller'),
  BoatEquipment: () => import('#controllers/boat_equipment_controller'),
  BoatMaintenanceTasks: () => import('#controllers/boat_maintenance_tasks_controller'),
  BoatMaintenances: () => import('#controllers/boat_maintenances_controller'),
  Boats: () => import('#controllers/boats_controller'),
  Home: () => import('#controllers/home_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
}
