/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  BoatMaintenances: () => import('#controllers/boat_maintenances_controller'),
  Boats: () => import('#controllers/boats_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
}
