/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import OrganizationMemberJoined from '#events/organization_member_joined'
import SimulatorLeadCreated from '#events/simulator_lead_created'
import OrganizationPlanDowngraded from '#events/organization_plan_downgraded'

export const events = {
  OrganizationMemberJoined: OrganizationMemberJoined,
  SimulatorLeadCreated: SimulatorLeadCreated,
  OrganizationPlanDowngraded: OrganizationPlanDowngraded,
}
