/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

import SimulatorLeadCreated from '#events/simulator_lead_created'

export const events = {
  SimulatorLeadCreated: SimulatorLeadCreated,
}
