/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const listeners = {
  LogAiKeyUndecryptable: () => import('#listeners/log_ai_key_undecryptable'),
  OnBoatStatusChanged: () => import('#listeners/on_boat_status_changed'),
  OnContactMessageReceived: () => import('#listeners/on_contact_message_received'),
  OnIncidentChanged: () => import('#listeners/on_incident_changed'),
  OnInvoicePaid: () => import('#listeners/on_invoice_paid'),
  OnMaintenanceTaskAssigned: () => import('#listeners/on_maintenance_task_assigned'),
  OnOrganizationInvitationAccepted: () => import('#listeners/on_organization_invitation_accepted'),
  OnOrganizationMemberJoined: () => import('#listeners/on_organization_member_joined'),
  OnOrganizationMemberRemoved: () => import('#listeners/on_organization_member_removed'),
  OnOrganizationMemberRoleChanged: () => import('#listeners/on_organization_member_role_changed'),
  OnOrganizationModuleDeactivated: () => import('#listeners/on_organization_module_deactivated'),
  OnOrganizationPlanDowngraded: () => import('#listeners/on_organization_plan_downgraded'),
  OnOrganizationPlanUpgraded: () => import('#listeners/on_organization_plan_upgraded'),
  OnPublicBookingDecided: () => import('#listeners/on_public_booking_decided'),
  OnPublicBookingRequested: () => import('#listeners/on_public_booking_requested'),
  OnReservationChanged: () => import('#listeners/on_reservation_changed'),
  OnSimulatorLeadCreated: () => import('#listeners/on_simulator_lead_created'),
  SendAiTokenQuotaNotification: () => import('#listeners/send_ai_token_quota_notification'),
  SendStorageQuotaNotification: () => import('#listeners/send_storage_quota_notification'),
}
