/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const listeners = {
  OnOrganizationMemberJoined: () => import('#listeners/on_organization_member_joined'),
  OnOrganizationPlanDowngraded: () => import('#listeners/on_organization_plan_downgraded'),
  OnSimulatorLeadCreated: () => import('#listeners/on_simulator_lead_created'),
  SendStorageQuotaNotification: () => import('#listeners/send_storage_quota_notification'),
}
