export const policies = {
  BoatPolicy: () => import('#policies/boat_policy'),
  ClientPolicy: () => import('#policies/client_policy'),
  CrewMemberPolicy: () => import('#policies/crew_member_policy'),
  FuelLogPolicy: () => import('#policies/fuel_log_policy'),
  IncidentPolicy: () => import('#policies/incident_policy'),
  InspectionPolicy: () => import('#policies/inspection_policy'),
  InvoicePolicy: () => import('#policies/invoice_policy'),
  MaintenancePolicy: () => import('#policies/maintenance_policy'),
  MouillagePolicy: () => import('#policies/mouillage_policy'),
  NavigationLogPolicy: () => import('#policies/navigation_log_policy'),
  OrganizationInvitationPolicy: () => import('#policies/organization_invitation_policy'),
  OrganizationPolicy: () => import('#policies/organization_policy'),
  PortPolicy: () => import('#policies/port_policy'),
  PricingSeasonPolicy: () => import('#policies/pricing_season_policy'),
  SimulatorPolicy: () => import('#policies/simulator_policy'),
  SpotPolicy: () => import('#policies/spot_policy'),
  SubscriptionPolicy: () => import('#policies/subscription_policy'),
}

