/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BoatEngineSchema extends BaseModel {
  static $columns = [
    'boatId',
    'brand',
    'createdAt',
    'fuel',
    'hours',
    'id',
    'kind',
    'manufacturedAt',
    'model',
    'powerHp',
    'powerKw',
    'serialNumber',
    'updatedAt',
  ] as const
  $columns = BoatEngineSchema.$columns
  @column()
  declare boatId: number
  @column()
  declare brand: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fuel: string | null
  @column()
  declare hours: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column.date()
  declare manufacturedAt: DateTime | null
  @column()
  declare model: string | null
  @column()
  declare powerHp: number | null
  @column()
  declare powerKw: number | null
  @column()
  declare serialNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatMaintenanceEventSchema extends BaseModel {
  static $columns = [
    'boatEngineId',
    'boatId',
    'boatRigId',
    'boatSailId',
    'createdAt',
    'dueAt',
    'engineCaption',
    'id',
    'notes',
    'performedAt',
    'sailCaption',
    'subject',
    'title',
    'updatedAt',
  ] as const
  $columns = BoatMaintenanceEventSchema.$columns
  @column()
  declare boatEngineId: number | null
  @column()
  declare boatId: number
  @column()
  declare boatRigId: number | null
  @column()
  declare boatSailId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dueAt: DateTime | null
  @column()
  declare engineCaption: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column.date()
  declare performedAt: DateTime
  @column()
  declare sailCaption: string | null
  @column()
  declare subject: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatMaintenancePartSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'maintenanceEventId',
    'name',
    'notes',
    'quantity',
    'updatedAt',
  ] as const
  $columns = BoatMaintenancePartSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maintenanceEventId: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare quantity: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatMaintenanceTaskSchema extends BaseModel {
  static $columns = [
    'boatEngineId',
    'boatId',
    'boatRigId',
    'boatSailId',
    'createdAt',
    'doneAt',
    'doneEngineHours',
    'dueAt',
    'dueEngineHours',
    'id',
    'lastDoneEngineHours',
    'notes',
    'recurrenceIntervalEngineHours',
    'recurrenceIntervalMonths',
    'status',
    'subject',
    'title',
    'updatedAt',
  ] as const
  $columns = BoatMaintenanceTaskSchema.$columns
  @column()
  declare boatEngineId: number | null
  @column()
  declare boatId: number
  @column()
  declare boatRigId: number | null
  @column()
  declare boatSailId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare doneAt: DateTime | null
  @column()
  declare doneEngineHours: number | null
  @column.date()
  declare dueAt: DateTime | null
  @column()
  declare dueEngineHours: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastDoneEngineHours: number | null
  @column()
  declare notes: string | null
  @column()
  declare recurrenceIntervalEngineHours: number | null
  @column()
  declare recurrenceIntervalMonths: number | null
  @column()
  declare status: string
  @column()
  declare subject: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatRigSchema extends BaseModel {
  static $columns = [
    'boatId',
    'createdAt',
    'id',
    'manufacturedAt',
    'mastCount',
    'rigType',
    'spreaders',
    'updatedAt',
  ] as const
  $columns = BoatRigSchema.$columns
  @column()
  declare boatId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare manufacturedAt: DateTime | null
  @column()
  declare mastCount: number | null
  @column()
  declare rigType: string
  @column()
  declare spreaders: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatSailSchema extends BaseModel {
  static $columns = [
    'areaM2',
    'boatId',
    'createdAt',
    'id',
    'manufacturedAt',
    'material',
    'reefPoints',
    'sailType',
    'updatedAt',
  ] as const
  $columns = BoatSailSchema.$columns
  @column()
  declare areaM2: number | null
  @column()
  declare boatId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare manufacturedAt: DateTime | null
  @column()
  declare material: string | null
  @column()
  declare reefPoints: number | null
  @column()
  declare sailType: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatSchema extends BaseModel {
  static $columns = [
    'beamM',
    'createdAt',
    'draftM',
    'hullMaterial',
    'id',
    'lengthM',
    'manufacturedAt',
    'manufacturer',
    'mastHeightM',
    'model',
    'name',
    'organizationId',
    'propulsionType',
    'registrationNumber',
    'type',
    'updatedAt',
    'yearBuilt',
  ] as const
  $columns = BoatSchema.$columns
  @column()
  declare beamM: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare draftM: number | null
  @column()
  declare hullMaterial: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lengthM: number | null
  @column.date()
  declare manufacturedAt: DateTime | null
  @column()
  declare manufacturer: string | null
  @column()
  declare mastHeightM: number | null
  @column()
  declare model: string | null
  @column()
  declare name: string
  @column()
  declare organizationId: number
  @column()
  declare propulsionType: string | null
  @column()
  declare registrationNumber: string | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare yearBuilt: number | null
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QueueJobSchema extends BaseModel {
  static $columns = [
    'acquiredAt',
    'data',
    'error',
    'executeAt',
    'finishedAt',
    'id',
    'queue',
    'score',
    'status',
    'workerId',
  ] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'cronExpression',
    'everyMs',
    'fromDate',
    'id',
    'lastRunAt',
    'name',
    'nextRunAt',
    'payload',
    'runCount',
    'runLimit',
    'status',
    'timezone',
    'toDate',
  ] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'organizationId',
    'password',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
