/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AiAnalysisSchema extends BaseModel {
  static $columns = ['boatId', 'createdAt', 'id', 'kind', 'responseText', 'userId'] as const
  $columns = AiAnalysisSchema.$columns
  @column()
  declare boatId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare responseText: string
  @column()
  declare userId: number
}

export class BoatEnginePartSchema extends BaseModel {
  static $columns = [
    'boatEngineId',
    'createdAt',
    'designation',
    'id',
    'minStockAlert',
    'notes',
    'reference',
    'stock',
    'supplier',
    'updatedAt',
    'wearState',
  ] as const
  $columns = BoatEnginePartSchema.$columns
  @column()
  declare boatEngineId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare designation: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare minStockAlert: number | null
  @column()
  declare notes: string | null
  @column()
  declare reference: string | null
  @column()
  declare stock: number | null
  @column()
  declare supplier: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare wearState: string | null
}

export class BoatEngineSchema extends BaseModel {
  static $columns = [
    'boatId',
    'brand',
    'createdAt',
    'fuel',
    'hours',
    'id',
    'installHours',
    'kind',
    'manufacturedAt',
    'model',
    'notes',
    'powerHp',
    'powerKw',
    'serialNumber',
    'status',
    'strokeType',
    'updatedAt',
  ] as const
  $columns = BoatEngineSchema.$columns
  @column()
  declare boatId: number
  @column()
  declare brand: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fuel: string | null
  @column()
  declare hours: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare installHours: number | null
  @column()
  declare kind: string
  @column.date()
  declare manufacturedAt: DateTime | null
  @column()
  declare model: string | null
  @column()
  declare notes: string | null
  @column()
  declare powerHp: number | null
  @column()
  declare powerKw: number | null
  @column()
  declare serialNumber: string | null
  @column()
  declare status: string
  @column()
  declare strokeType: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatMaintenanceEventSchema extends BaseModel {
  static $columns = [
    'boatEngineId',
    'boatId',
    'boatRigId',
    'boatSailId',
    'createdAt',
    'dueAt',
    'engineCaption',
    'id',
    'notes',
    'performedAt',
    'sailCaption',
    'subject',
    'title',
    'updatedAt',
  ] as const
  $columns = BoatMaintenanceEventSchema.$columns
  @column()
  declare boatEngineId: number | null
  @column()
  declare boatId: number
  @column()
  declare boatRigId: number | null
  @column()
  declare boatSailId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dueAt: DateTime | null
  @column()
  declare engineCaption: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column.date()
  declare performedAt: DateTime
  @column()
  declare sailCaption: string | null
  @column()
  declare subject: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatMaintenancePartSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'enginePartId',
    'id',
    'maintenanceEventId',
    'name',
    'notes',
    'quantity',
    'unitPrice',
    'updatedAt',
  ] as const
  $columns = BoatMaintenancePartSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enginePartId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maintenanceEventId: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare quantity: number | null
  @column()
  declare unitPrice: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatMaintenanceSheetItemSchema extends BaseModel {
  static $columns = [
    'boatMaintenanceSheetId',
    'createdAt',
    'id',
    'isDone',
    'label',
    'notes',
    'position',
    'updatedAt',
  ] as const
  $columns = BoatMaintenanceSheetItemSchema.$columns
  @column()
  declare boatMaintenanceSheetId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDone: boolean
  @column()
  declare label: string
  @column()
  declare notes: string | null
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatMaintenanceSheetSchema extends BaseModel {
  static $columns = [
    'boatId',
    'createdAt',
    'id',
    'notes',
    'performedAt',
    'status',
    'title',
    'type',
    'updatedAt',
  ] as const
  $columns = BoatMaintenanceSheetSchema.$columns
  @column()
  declare boatId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column.date()
  declare performedAt: DateTime
  @column()
  declare status: string
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatMaintenanceTaskSchema extends BaseModel {
  static $columns = [
    'boatEngineId',
    'boatId',
    'boatRigId',
    'boatSailId',
    'createdAt',
    'doneAt',
    'doneEngineHours',
    'dueAt',
    'dueEngineHours',
    'id',
    'lastDoneEngineHours',
    'notes',
    'recurrenceIntervalEngineHours',
    'recurrenceIntervalMonths',
    'status',
    'subject',
    'title',
    'updatedAt',
  ] as const
  $columns = BoatMaintenanceTaskSchema.$columns
  @column()
  declare boatEngineId: number | null
  @column()
  declare boatId: number
  @column()
  declare boatRigId: number | null
  @column()
  declare boatSailId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare doneAt: DateTime | null
  @column()
  declare doneEngineHours: number | null
  @column.date()
  declare dueAt: DateTime | null
  @column()
  declare dueEngineHours: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastDoneEngineHours: number | null
  @column()
  declare notes: string | null
  @column()
  declare recurrenceIntervalEngineHours: number | null
  @column()
  declare recurrenceIntervalMonths: number | null
  @column()
  declare status: string
  @column()
  declare subject: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatPositionHistorySchema extends BaseModel {
  static $columns = [
    'boatId',
    'createdAt',
    'endedAt',
    'id',
    'notes',
    'spotId',
    'startedAt',
    'updatedAt',
  ] as const
  $columns = BoatPositionHistorySchema.$columns
  @column()
  declare boatId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare spotId: number | null
  @column.dateTime()
  declare startedAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatRigSchema extends BaseModel {
  static $columns = [
    'boatId',
    'createdAt',
    'id',
    'manufacturedAt',
    'mastCount',
    'notes',
    'rigType',
    'spreaders',
    'status',
    'updatedAt',
  ] as const
  $columns = BoatRigSchema.$columns
  @column()
  declare boatId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare manufacturedAt: DateTime | null
  @column()
  declare mastCount: number | null
  @column()
  declare notes: string | null
  @column()
  declare rigType: string
  @column()
  declare spreaders: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatSafetyEquipmentSchema extends BaseModel {
  static $columns = [
    'boatId',
    'createdAt',
    'equipmentType',
    'expiryDate',
    'id',
    'notes',
    'quantity',
    'status',
    'updatedAt',
  ] as const
  $columns = BoatSafetyEquipmentSchema.$columns
  @column()
  declare boatId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare equipmentType: string
  @column.date()
  declare expiryDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare quantity: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatSailSchema extends BaseModel {
  static $columns = [
    'areaM2',
    'boatId',
    'createdAt',
    'id',
    'manufacturedAt',
    'material',
    'notes',
    'reefPoints',
    'sailType',
    'status',
    'updatedAt',
  ] as const
  $columns = BoatSailSchema.$columns
  @column()
  declare areaM2: number | null
  @column()
  declare boatId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare manufacturedAt: DateTime | null
  @column()
  declare material: string | null
  @column()
  declare notes: string | null
  @column()
  declare reefPoints: number | null
  @column()
  declare sailType: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BoatSchema extends BaseModel {
  static $columns = [
    'beamM',
    'createdAt',
    'draftM',
    'flagCountry',
    'francisationNumber',
    'homePort',
    'hullIdentificationNumber',
    'hullMaterial',
    'id',
    'lengthM',
    'manufacturedAt',
    'manufacturer',
    'mastHeightM',
    'maxPersons',
    'model',
    'name',
    'navigationCategory',
    'organizationId',
    'propulsionType',
    'registrationNumber',
    'spotId',
    'type',
    'updatedAt',
    'yearBuilt',
  ] as const
  $columns = BoatSchema.$columns
  @column()
  declare beamM: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare draftM: number | null
  @column()
  declare flagCountry: string | null
  @column()
  declare francisationNumber: string | null
  @column()
  declare homePort: string | null
  @column()
  declare hullIdentificationNumber: string | null
  @column()
  declare hullMaterial: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lengthM: number | null
  @column.date()
  declare manufacturedAt: DateTime | null
  @column()
  declare manufacturer: string | null
  @column()
  declare mastHeightM: number | null
  @column()
  declare maxPersons: number | null
  @column()
  declare model: string | null
  @column()
  declare name: string
  @column()
  declare navigationCategory: string | null
  @column()
  declare organizationId: number
  @column()
  declare propulsionType: string | null
  @column()
  declare registrationNumber: string | null
  @column()
  declare spotId: number | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare yearBuilt: number | null
}

export class MediaSchema extends BaseModel {
  static $columns = [
    'bytes',
    'caption',
    'cloudinaryPublicId',
    'createdAt',
    'entityId',
    'entityType',
    'format',
    'height',
    'id',
    'kind',
    'originalFilename',
    'position',
    'secureUrl',
    'updatedAt',
    'uploadedById',
    'width',
  ] as const
  $columns = MediaSchema.$columns
  @column()
  declare bytes: number
  @column()
  declare caption: string | null
  @column()
  declare cloudinaryPublicId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: number
  @column()
  declare entityType: string
  @column()
  declare format: string
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare originalFilename: string
  @column()
  declare position: number
  @column()
  declare secureUrl: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uploadedById: number | null
  @column()
  declare width: number | null
}

export class MouillageSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'id',
    'name',
    'portId',
    'positionX',
    'positionY',
    'updatedAt',
  ] as const
  $columns = MouillageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare portId: number
  @column()
  declare positionX: number | null
  @column()
  declare positionY: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationInvitationSchema extends BaseModel {
  static $columns = [
    'acceptedAt',
    'createdAt',
    'email',
    'expiresAt',
    'id',
    'invitedById',
    'organizationId',
    'role',
    'status',
    'token',
    'updatedAt',
  ] as const
  $columns = OrganizationInvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedById: number | null
  @column()
  declare organizationId: number
  @column()
  declare role: string
  @column()
  declare status: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationMembershipSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'organizationId', 'role', 'updatedAt', 'userId'] as const
  $columns = OrganizationMembershipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class OrganizationSchema extends BaseModel {
  static $columns = [
    'aiModelOverride',
    'aiSystemPrompt',
    'createdAt',
    'id',
    'name',
    'plan',
    'slug',
    'storageUsedBytes',
    'stripeCustomerId',
    'updatedAt',
  ] as const
  $columns = OrganizationSchema.$columns
  @column()
  declare aiModelOverride: string | null
  @column()
  declare aiSystemPrompt: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare plan: string
  @column()
  declare slug: string
  @column()
  declare storageUsedBytes: number
  @column()
  declare stripeCustomerId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'expiresAt', 'id', 'token'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
}

export class PontoonSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'id',
    'name',
    'portId',
    'positionX',
    'positionY',
    'updatedAt',
  ] as const
  $columns = PontoonSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare portId: number
  @column()
  declare positionX: number | null
  @column()
  declare positionY: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PortSchema extends BaseModel {
  static $columns = [
    'address',
    'city',
    'country',
    'createdAt',
    'id',
    'name',
    'notes',
    'organizationId',
    'updatedAt',
  ] as const
  $columns = PortSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare organizationId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QueueDedupKeySchema extends BaseModel {
  static $columns = [
    'completedAt',
    'createdAt',
    'jobName',
    'key',
    'lastError',
    'payloadHash',
    'queue',
    'queueJobId',
    'status',
    'updatedAt',
  ] as const
  $columns = QueueDedupKeySchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare jobName: string
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare lastError: string | null
  @column()
  declare payloadHash: string | null
  @column()
  declare queue: string
  @column()
  declare queueJobId: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class QueueJobSchema extends BaseModel {
  static $columns = [
    'acquiredAt',
    'data',
    'error',
    'executeAt',
    'finishedAt',
    'id',
    'queue',
    'score',
    'status',
    'workerId',
  ] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'cronExpression',
    'everyMs',
    'fromDate',
    'id',
    'lastRunAt',
    'name',
    'nextRunAt',
    'payload',
    'runCount',
    'runLimit',
    'status',
    'timezone',
    'toDate',
  ] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SimulatorLeadSchema extends BaseModel {
  static $columns = [
    'boatType',
    'createdAt',
    'email',
    'engineWear',
    'hullWear',
    'id',
    'lengthM',
    'locale',
    'riggingWear',
    'safetyWear',
    'totalMax',
    'totalMin',
    'winteringZone',
  ] as const
  $columns = SimulatorLeadSchema.$columns
  @column()
  declare boatType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare engineWear: string | null
  @column()
  declare hullWear: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lengthM: number
  @column()
  declare locale: string
  @column()
  declare riggingWear: string | null
  @column()
  declare safetyWear: string | null
  @column()
  declare totalMax: number
  @column()
  declare totalMin: number
  @column()
  declare winteringZone: string | null
}

export class SimulatorShareSchema extends BaseModel {
  static $columns = ['breakdown', 'createdAt', 'id', 'input', 'locale', 'token'] as const
  $columns = SimulatorShareSchema.$columns
  @column()
  declare breakdown: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare input: any
  @column()
  declare locale: string
  @column()
  declare token: string
}

export class SpotSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'id',
    'mouillageId',
    'name',
    'organizationId',
    'pontoonId',
    'updatedAt',
  ] as const
  $columns = SpotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mouillageId: number | null
  @column()
  declare name: string
  @column()
  declare organizationId: number
  @column()
  declare pontoonId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SubscriptionSchema extends BaseModel {
  static $columns = [
    'billingInterval',
    'cancelAtPeriodEnd',
    'createdAt',
    'currentPeriodEnd',
    'currentPeriodStart',
    'id',
    'organizationId',
    'planTier',
    'status',
    'stripePriceId',
    'stripeSubscriptionId',
    'updatedAt',
  ] as const
  $columns = SubscriptionSchema.$columns
  @column()
  declare billingInterval: string
  @column()
  declare cancelAtPeriodEnd: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare currentPeriodEnd: DateTime
  @column.dateTime()
  declare currentPeriodStart: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number
  @column()
  declare planTier: string
  @column()
  declare status: string
  @column()
  declare stripePriceId: string
  @column()
  declare stripeSubscriptionId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'lastLoginAt',
    'organizationId',
    'password',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare organizationId: number | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
