/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type BoatEngineTransformer from '#transformers/boat_engine_transformer'
import type BoatInspectionTransformer from '#transformers/boat_inspection_transformer'
import type BoatPricingTransformer from '#transformers/boat_pricing_transformer'
import type BoatReservationTransformer from '#transformers/boat_reservation_transformer'
import type BoatTransformer from '#transformers/boat_transformer'
import type BudgetTransformer from '#transformers/budget_transformer'
import type ClientTransformer from '#transformers/client_transformer'
import type InvoiceTransformer from '#transformers/invoice_transformer'
import type MaintenanceTransformer from '#transformers/maintenance_transformer'
import type MediaTransformer from '#transformers/media_transformer'
import type MouillageTransformer from '#transformers/mouillage_transformer'
import type NotificationTransformer from '#transformers/notification_transformer'
import type OrganizationTransformer from '#transformers/organization_transformer'
import type PontoonTransformer from '#transformers/pontoon_transformer'
import type PortTransformer from '#transformers/port_transformer'
import type RentalContractTransformer from '#transformers/rental_contract_transformer'
import type SimulatorTransformer from '#transformers/simulator_transformer'
import type SpotTransformer from '#transformers/spot_transformer'
import type SubscriptionTransformer from '#transformers/subscription_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type BoatEngine = InferData<BoatEngineTransformer>
  export namespace BoatEngine {
    export type Variants = InferVariants<BoatEngineTransformer>
  }
  export type BoatInspection = InferData<BoatInspectionTransformer>
  export namespace BoatInspection {
    export type Variants = InferVariants<BoatInspectionTransformer>
  }
  export type BoatPricing = InferData<BoatPricingTransformer>
  export namespace BoatPricing {
    export type Variants = InferVariants<BoatPricingTransformer>
  }
  export type BoatReservation = InferData<BoatReservationTransformer>
  export namespace BoatReservation {
    export type Variants = InferVariants<BoatReservationTransformer>
  }
  export type Boat = InferData<BoatTransformer>
  export namespace Boat {
    export type Variants = InferVariants<BoatTransformer>
  }
  export type Budget = InferData<BudgetTransformer>
  export namespace Budget {
    export type Variants = InferVariants<BudgetTransformer>
  }
  export type Client = InferData<ClientTransformer>
  export namespace Client {
    export type Variants = InferVariants<ClientTransformer>
  }
  export type Invoice = InferData<InvoiceTransformer>
  export namespace Invoice {
    export type Variants = InferVariants<InvoiceTransformer>
  }
  export type Maintenance = InferData<MaintenanceTransformer>
  export namespace Maintenance {
    export type Variants = InferVariants<MaintenanceTransformer>
  }
  export type Media = InferData<MediaTransformer>
  export namespace Media {
    export type Variants = InferVariants<MediaTransformer>
  }
  export type Mouillage = InferData<MouillageTransformer>
  export namespace Mouillage {
    export type Variants = InferVariants<MouillageTransformer>
  }
  export type Notification = InferData<NotificationTransformer>
  export namespace Notification {
    export type Variants = InferVariants<NotificationTransformer>
  }
  export type Organization = InferData<OrganizationTransformer>
  export namespace Organization {
    export type Variants = InferVariants<OrganizationTransformer>
  }
  export type Pontoon = InferData<PontoonTransformer>
  export namespace Pontoon {
    export type Variants = InferVariants<PontoonTransformer>
  }
  export type Port = InferData<PortTransformer>
  export namespace Port {
    export type Variants = InferVariants<PortTransformer>
  }
  export type RentalContract = InferData<RentalContractTransformer>
  export namespace RentalContract {
    export type Variants = InferVariants<RentalContractTransformer>
  }
  export type Simulator = InferData<SimulatorTransformer>
  export namespace Simulator {
    export type Variants = InferVariants<SimulatorTransformer>
  }
  export type Spot = InferData<SpotTransformer>
  export namespace Spot {
    export type Variants = InferVariants<SpotTransformer>
  }
  export type Subscription = InferData<SubscriptionTransformer>
  export namespace Subscription {
    export type Variants = InferVariants<SubscriptionTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
