import type { AiSuggestionLocale } from '#shared/types/ai'
import type { AssistantNavTarget } from '#shared/types/assistant'
import type { AssistantToolPlanFlag } from '#shared/types/assistant_tools'

/**
 * Base de connaissance produit du copilote FleetAi (#642).
 *
 * Curée et versionnée — pas d'embeddings : l'outil `search_product_help`
 * score ces entrées sur mots-clés, titre puis corps. À compléter à chaque
 * nouvelle feature (règle CLAUDE.md).
 */
export interface ProductHelpEntry {
  id: string
  title: Record<AiSuggestionLocale, string>
  /** 400 à 800 caractères par locale. */
  body: Record<AiSuggestionLocale, string>
  /** FR et EN, normalisés : minuscules, sans accents. */
  keywords: string[]
  navTarget: AssistantNavTarget | null
  planFlag?: AssistantToolPlanFlag
}

export const PRODUCT_KNOWLEDGE: ProductHelpEntry[] = [
  {
    id: 'dashboard-overview',
    title: {
      en: 'Dashboard: fleet overview and urgent maintenance',
      fr: 'Tableau de bord : vue flotte et maintenance urgente',
    },
    body: {
      en: 'The dashboard is the landing page after login. It shows fleet counters (boats, engines, sails, rigs), a summary table of your boats, and the list of urgent maintenance. A task is urgent when its due date falls within the next 14 days, or, for engine-hour tasks, when fewer than 10 engine hours remain before the due threshold (based on current engine hours). From the dashboard you can also launch the AI fleet analysis when your plan includes AI features.',
      fr: 'Le tableau de bord est la page d’accueil une fois connecté. Il affiche les compteurs de la flotte (bateaux, moteurs, voiles, gréements), un tableau résumé de vos bateaux et la liste de la maintenance urgente. Une tâche est urgente quand son échéance tombe dans les 14 prochains jours ou, pour une tâche en heures moteur, quand il reste moins de 10 heures avant le seuil (calculé sur les heures moteur courantes). Depuis le tableau de bord, vous pouvez aussi lancer l’analyse IA de flotte si votre plan inclut l’IA.',
    },
    keywords: [
      'dashboard',
      'tableau de bord',
      'accueil',
      'vue d ensemble',
      'overview',
      'urgent',
      'stats',
      'compteurs',
      'flotte',
      'fleet',
    ],
    navTarget: 'dashboard',
  },
  {
    id: 'boats-create',
    title: {
      en: 'Add a boat',
      fr: 'Ajouter un bateau',
    },
    body: {
      en: 'Create a boat from the Boats page via the New boat button (/boats/new). A brand and model catalog assists input: picking a brand loads its models, but free text is always accepted — a boat outside the catalog is perfectly valid. You pick a category from a closed list (optional), the propulsion type, and hull specifications. For a sailboat, mast height is required. Each boat then gets its own page with tabs for tasks, history, sheets, equipment, navigation and documents.',
      fr: 'Créez un bateau depuis la page Bateaux via le bouton Nouveau bateau (/boats/new). Un catalogue de marques et modèles assiste la saisie : choisir une marque charge ses modèles, mais la saisie libre reste toujours acceptée — un bateau hors catalogue est parfaitement valide. Vous choisissez une catégorie dans une liste fermée (facultative), le type de propulsion et les caractéristiques de coque. Pour un voilier, la hauteur de mât est requise. Chaque bateau dispose ensuite de sa fiche à onglets : tâches, historique, fiches, équipements, navigation, documents.',
    },
    keywords: [
      'bateau',
      'boat',
      'creer',
      'create',
      'ajouter',
      'add',
      'nouveau',
      'catalogue',
      'marque',
      'modele',
      'brand',
      'model',
    ],
    navTarget: 'boats.index',
  },
  {
    id: 'boats-hull-fields',
    title: {
      en: 'Boat details: category, flag, CE category and armament zone',
      fr: 'Fiche bateau : catégorie, pavillon, catégorie CE et zone d’armement',
    },
    body: {
      en: 'A boat record carries several distinct classification fields. The category (motorboat, sailboat, catamaran, RIB…) comes from a closed vocabulary and drives things like the inspection checklist. The CE navigation category (A to D) describes the design of the hull. The armament zone (basic, coastal, semi-offshore, offshore) is the distance from shelter declared for Division 240 safety checks — it is independent from the CE category. The flag country and port country use the ISO country list; the home port is free text assisted by your ports.',
      fr: 'La fiche bateau porte plusieurs champs de classification distincts. La catégorie (vedette, voilier, catamaran, semi-rigide…) vient d’un vocabulaire fermé et pilote par exemple la checklist d’état des lieux. La catégorie de navigation CE (A à D) décrit la conception de la coque. La zone d’armement (basique, côtier, semi-hauturier, hauturier) est la distance d’un abri déclarée pour les contrôles Division 240 — elle est indépendante de la catégorie CE. Le pavillon utilise la liste des pays ISO ; le port d’attache est un texte libre assisté par vos ports.',
    },
    keywords: [
      'coque',
      'hull',
      'pavillon',
      'flag',
      'categorie',
      'category',
      'ce',
      'zone armement',
      'armament zone',
      'port d attache',
      'home port',
    ],
    navTarget: 'boats.index',
  },
  {
    id: 'boats-equipment',
    title: {
      en: 'Boat equipment: engines, sails, rig, generic and safety gear',
      fr: 'Équipements du bateau : moteurs, voiles, gréement, divers et sécurité',
    },
    body: {
      en: 'Each boat page manages its equipment: engines (with brand, model, serial number, hours and motorization family), sails (with sailmaker referential and material), rig, generic equipment (electronics, energy, comfort, plumbing…) and safety equipment. Brand and model catalogs assist input for engines and equipment, free text always accepted. Every equipment item can carry photos, and engines also carry documents. Degraded equipment can be turned into an action (buy, replace, repair) in one click.',
      fr: 'Chaque fiche bateau gère ses équipements : moteurs (marque, modèle, numéro de série, heures et famille de motorisation), voiles (référentiel de voileries et matériau), gréement, équipements divers (électronique, énergie, confort, plomberie…) et équipements de sécurité. Des catalogues de marques et modèles assistent la saisie pour les moteurs et équipements, la saisie libre restant acceptée. Chaque équipement peut porter des photos, et les moteurs des documents. Un équipement dégradé peut devenir une action (acheter, remplacer, réparer) en un clic.',
    },
    keywords: [
      'equipement',
      'equipment',
      'voile',
      'sail',
      'greement',
      'rig',
      'securite',
      'safety',
      'photos',
      'moteur',
      'engine',
    ],
    navTarget: 'boats.index',
  },
  {
    id: 'engines-inventory',
    title: {
      en: 'Engine inventory across the fleet',
      fr: 'Inventaire des moteurs de la flotte',
    },
    body: {
      en: 'The Engines page (/engines) lists every engine of the organization across all boats. You can search by brand, model, serial number or boat name, and filter by boat, kind, status or motorization family, then sort by recency, brand or hours. Status counters (active, out of service…) are computed on the whole fleet, not just the current page. Each row links back to the engine on its boat page, where you edit hours, parts, documents and photos.',
      fr: 'La page Moteurs (/engines) liste tous les moteurs de l’organisation, tous bateaux confondus. Vous pouvez chercher par marque, modèle, numéro de série ou nom du bateau, filtrer par bateau, type, statut ou famille de motorisation, puis trier par récence, marque ou heures. Les compteurs par statut (actif, hors service…) sont calculés sur toute la flotte, pas seulement la page affichée. Chaque ligne renvoie vers le moteur sur sa fiche bateau, où vous modifiez heures, pièces, documents et photos.',
    },
    keywords: [
      'moteur',
      'moteurs',
      'engine',
      'engines',
      'inventaire',
      'inventory',
      'liste',
      'filtre',
      'statut',
      'famille',
    ],
    navTarget: 'engines.index',
  },
  {
    id: 'engine-hours',
    title: {
      en: 'Engine hours tracking',
      fr: 'Suivi des heures moteur',
    },
    body: {
      en: 'Engine hours are recorded per engine and drive hour-based maintenance. You can edit them on the engine form, and they are updated automatically when a trip is closed in the logbook: closing propagates the arrival engine hours to the targeted engine, or to the only active engine of the boat. Maintenance tasks can be due at a given engine-hour threshold, and the dashboard flags a task as urgent when fewer than 10 hours remain. Fuel logs can also record hours at refueling.',
      fr: 'Les heures moteur sont suivies par moteur et pilotent la maintenance en heures. Vous pouvez les modifier sur le formulaire du moteur, et elles sont mises à jour automatiquement à la clôture d’une sortie du journal de bord : la clôture propage les heures d’arrivée vers le moteur ciblé, ou vers l’unique moteur actif du bateau. Les tâches de maintenance peuvent être dues à un seuil d’heures, et le tableau de bord signale une tâche urgente quand il reste moins de 10 heures. Les avitaillements peuvent aussi noter les heures au plein.',
    },
    keywords: [
      'heures moteur',
      'engine hours',
      'compteur',
      'hours',
      'heures',
      'seuil',
      'echeance',
      'clotures',
      'sortie',
      'trip',
    ],
    navTarget: 'engines.index',
  },
  {
    id: 'maintenance-tasks',
    title: {
      en: 'Planned maintenance tasks',
      fr: 'Tâches de maintenance planifiées',
    },
    body: {
      en: 'A maintenance task is created on a boat with a title, a subject among ten (boat, hull, engine, sail, rig, electrical, plumbing, safety, deck, other), and at least one due condition: a due date and/or an engine-hour threshold. Hour-based tasks require the engine subject and a target engine. Marking a task done records the completion date and, for hour-based tasks, the engine hours at completion. Tasks live on the boat Tasks tab and feed the planning and the dashboard urgent list.',
      fr: 'Une tâche de maintenance se crée sur un bateau avec un titre, un sujet parmi dix (bateau, coque, moteur, voile, gréement, électricité, plomberie, sécurité, pont, autre) et au moins une échéance : une date et/ou un seuil d’heures moteur. Une tâche en heures exige le sujet moteur et un moteur cible. Marquer une tâche faite enregistre la date de réalisation et, pour une tâche en heures, les heures moteur au moment de la clôture. Les tâches vivent dans l’onglet Tâches du bateau et alimentent le planning et la liste urgente du tableau de bord.',
    },
    keywords: [
      'tache',
      'taches',
      'task',
      'maintenance',
      'entretien',
      'echeance',
      'due date',
      'planifier',
      'todo',
      'sujet',
    ],
    navTarget: 'planning.index',
  },
  {
    id: 'maintenance-recurrence',
    title: {
      en: 'Recurring maintenance',
      fr: 'Récurrence des tâches de maintenance',
    },
    body: {
      en: 'A maintenance task can carry a recurrence: an interval in months and/or in engine hours. When you mark a recurring task done, FleetAi automatically creates the next occurrence — due date equal to the completion date plus the month interval, or due hours equal to the completed engine hours plus the hour interval. This keeps periodic operations (oil change every 100 h, antifouling every 12 months…) rolling without manual re-entry. The standard operations catalog suggests typical intervals when creating a task.',
      fr: 'Une tâche de maintenance peut porter une récurrence : un intervalle en mois et/ou en heures moteur. Quand vous marquez une tâche récurrente comme faite, FleetAi crée automatiquement l’occurrence suivante — échéance égale à la date de réalisation plus l’intervalle en mois, ou seuil égal aux heures moteur de clôture plus l’intervalle en heures. Les opérations périodiques (vidange toutes les 100 h, antifouling tous les 12 mois…) s’enchaînent ainsi sans ressaisie. Le catalogue d’opérations standard suggère des intervalles types à la création.',
    },
    keywords: [
      'recurrence',
      'recurring',
      'intervalle',
      'interval',
      'periodicite',
      'vidange',
      'oil change',
      'mois',
      'heures',
      'automatique',
    ],
    navTarget: 'planning.index',
  },
  {
    id: 'maintenance-operations-catalog',
    title: {
      en: 'Standard maintenance operations catalog',
      fr: 'Catalogue d’opérations d’entretien standard',
    },
    body: {
      en: 'When creating a maintenance task or history event, the title field is a combobox fed by a catalog of about 95 named operations across the ten subjects, each with indicative intervals in months or engine hours. Picking an operation fills the title, aligns the subject and pre-fills empty recurrence intervals — a value you already typed is never overwritten. Free text remains accepted as-is. Engine operations are filtered by the motorization family of your engines (no spark plugs suggested on a diesel).',
      fr: 'À la création d’une tâche ou d’un événement d’entretien, le champ titre est une combobox alimentée par un catalogue d’environ 95 opérations nommées réparties sur les dix sujets, avec des périodicités indicatives en mois ou en heures moteur. Retenir une opération remplit le titre, aligne le sujet et complète les intervalles de récurrence encore vides — une valeur déjà saisie n’est jamais écrasée. La saisie libre reste acceptée telle quelle. Les opérations moteur sont filtrées par la famille de motorisation (pas de bougies sur un diesel).',
    },
    keywords: [
      'operations',
      'catalogue',
      'catalog',
      'standard',
      'combobox',
      'periodicite',
      'intervalles',
      'suggestions',
      'titre',
      'entretien',
    ],
    navTarget: null,
  },
  {
    id: 'maintenance-history',
    title: {
      en: 'Maintenance history (events)',
      fr: 'Historique d’entretien (événements)',
    },
    body: {
      en: 'The maintenance history records what was actually done: each event has a date, one of the ten subjects, a title, optional notes and a list of replaced parts with quantities. Engine, sail or rig events are linked to the specific equipment. Events appear on the boat History tab in reverse chronological order, and the fleet-wide history page (/maintenance/history) aggregates all boats with filters. History can be exported to CSV per boat, and event titles feed the AI analysis of your fleet.',
      fr: 'L’historique d’entretien trace ce qui a réellement été fait : chaque événement porte une date, l’un des dix sujets, un titre, des notes et une liste de pièces remplacées avec quantités. Les événements moteur, voile ou gréement sont liés à l’équipement concerné. Ils s’affichent dans l’onglet Historique du bateau, du plus récent au plus ancien, et la page d’historique flotte (/maintenance/history) agrège tous les bateaux avec filtres. L’historique s’exporte en CSV par bateau, et les titres alimentent l’analyse IA de la flotte.',
    },
    keywords: [
      'historique',
      'history',
      'evenement',
      'event',
      'entretien',
      'maintenance',
      'pieces remplacees',
      'parts',
      'journal',
      'interventions',
    ],
    navTarget: 'maintenance.history',
  },
  {
    id: 'maintenance-sheets',
    title: {
      en: 'Maintenance sheets (guided checklists)',
      fr: 'Fiches d’entretien (checklists guidées)',
    },
    body: {
      en: 'Maintenance sheets are guided checklists for standard nautical operations. Nine types exist: routine care, rigging setup, winterization, de-winterization, workshop, engine season start/end, careening, catamaran specifics and RIB specifics — each pre-filled with 8 to 14 default items in your language. Every item is checkable with an optional note, including offline; when all items are checked the sheet can be marked completed (a final state). Sheets live in the Sheets tab of the boat page.',
      fr: 'Les fiches d’entretien sont des checklists guidées pour des opérations nautiques standard. Neuf types existent : entretien courant, montage, hivernage, déhivernage, atelier, mise en route/fin de saison moteur, carénage, spécifiques catamaran et semi-rigide — chacun pré-rempli avec 8 à 14 items par défaut dans votre langue. Chaque item se coche individuellement avec une note optionnelle, y compris hors-ligne ; quand tout est coché, la fiche peut être marquée terminée (état définitif). Les fiches vivent dans l’onglet Fiches de la fiche bateau.',
    },
    keywords: [
      'fiche',
      'fiches',
      'sheet',
      'checklist',
      'hivernage',
      'winterization',
      'carenage',
      'montage',
      'atelier',
      'entretien',
    ],
    navTarget: 'boats.index',
  },
  {
    id: 'planning-kanban',
    title: {
      en: 'Planning: kanban and calendar',
      fr: 'Planning : kanban et calendrier',
    },
    body: {
      en: 'The Planning page (/planning) shows all open maintenance tasks of the organization in two views. The kanban board splits tasks into columns — overdue, due soon, planned and done — so you see at a glance what needs attention across the fleet. The calendar view places date-based tasks on a monthly grid. Both views cover every boat of the organization; tasks themselves are created and completed from each boat page or proposed by the FleetAi copilot.',
      fr: 'La page Planning (/planning) montre toutes les tâches de maintenance ouvertes de l’organisation sous deux vues. Le kanban répartit les tâches en colonnes — en retard, bientôt dues, planifiées et faites — pour voir d’un coup d’œil ce qui demande attention sur la flotte. La vue calendrier place les tâches datées sur une grille mensuelle. Les deux vues couvrent tous les bateaux de l’organisation ; les tâches se créent et se clôturent depuis chaque fiche bateau, ou sur proposition du copilote FleetAi.',
    },
    keywords: [
      'planning',
      'kanban',
      'calendrier',
      'calendar',
      'colonnes',
      'en retard',
      'overdue',
      'planifie',
      'vue',
      'taches',
    ],
    navTarget: 'planning.index',
  },
  {
    id: 'task-grouping',
    title: {
      en: 'Automatic task grouping',
      fr: 'Regroupement automatique des tâches',
    },
    body: {
      en: 'On Pro and Enterprise plans, the planning automatically groups open date-based tasks of the same boat and same subject whose due dates are within 7 days of each other, to help batch interventions. Groups appear as collapsible cards in the Planned column of the kanban, with the date range and task count. A toggle disables grouping for the session, and each group can be dissociated individually. Engine-hour tasks and done tasks are never grouped. Starter plans see an upgrade teaser instead.',
      fr: 'Sur les plans Pro et Entreprise, le planning regroupe automatiquement les tâches ouvertes à date d’un même bateau et d’un même sujet dont les échéances sont à 7 jours ou moins les unes des autres, pour faciliter la planification par lots. Les groupes apparaissent en cartes pliables dans la colonne Planifiées du kanban, avec la plage de dates et le nombre de tâches. Un interrupteur désactive le regroupement pour la session, et chaque groupe peut être dissocié. Les tâches en heures moteur et les tâches faites ne sont jamais regroupées.',
    },
    keywords: [
      'regroupement',
      'grouping',
      'groupes',
      'groups',
      'lots',
      'batch',
      'proximite',
      '7 jours',
      'kanban',
      'dissocier',
    ],
    navTarget: 'planning.index',
    planFlag: 'canGroupTasks',
  },
  {
    id: 'diagnostic-checklists',
    title: {
      en: 'Engine failure diagnostic checklists',
      fr: 'Checklists de diagnostic de panne moteur',
    },
    body: {
      en: 'The Diagnostic page (/diagnostic) guides you from a symptom to a probable cause, ordering checks from cheapest to most expensive. Eligible engines depend on their motorization family: 2-stroke outboards, inboard diesels (shaft line and saildrive), sterndrives and generators have content today. Each engine gets a global checklist plus detailed sheets (compression, ignition, fuel, cooling, gearbox, wet exhaust…). Every checked step is persisted per engine, so a diagnostic spread over several outings keeps its progress.',
      fr: 'La page Diagnostic (/diagnostic) vous guide d’un symptôme vers une cause probable, en ordonnant les contrôles du moins cher au plus cher. Les moteurs éligibles dépendent de leur famille de motorisation : hors-bord 2 temps, in-bord diesel (ligne d’arbre et saildrive), embases Z et groupes électrogènes ont du contenu aujourd’hui. Chaque moteur dispose d’une checklist globale et de fiches détaillées (compression, allumage, carburant, refroidissement, inverseur, échappement humide…). Chaque case cochée est persistée par moteur : un diagnostic étalé sur plusieurs sorties garde sa progression.',
    },
    keywords: [
      'diagnostic',
      'panne',
      'breakdown',
      'troubleshooting',
      'symptome',
      'checklist',
      'moteur',
      'engine',
      'surchauffe',
      'demarrage',
    ],
    navTarget: 'diagnostic.index',
  },
  {
    id: 'diagnostic-ai',
    title: {
      en: 'AI-assisted engine diagnosis',
      fr: 'Diagnostic de panne assisté par IA',
    },
    body: {
      en: 'On plans with AI, the diagnostic checklist offers an AI panel: describe the symptoms in your own words and the assistant, aware of the motorization family of the engine, suggests the most relevant diagnostic sheet and the checks to run first. The AI only recommends sheets that actually apply to the engine family — it never invents technical specifications and never replaces the workshop manual or a professional. Usage counts against the monthly AI token quota of the organization.',
      fr: 'Sur les plans avec IA, la checklist de diagnostic propose un panneau IA : décrivez les symptômes avec vos mots et l’assistant, qui connaît la famille de motorisation du moteur, recommande la fiche de diagnostic la plus pertinente et les contrôles à mener en premier. L’IA ne recommande que des fiches réellement applicables à la famille du moteur — elle n’invente jamais de spécification technique et ne remplace ni le manuel d’atelier ni un professionnel. L’usage est décompté du quota mensuel de tokens IA de l’organisation.',
    },
    keywords: [
      'diagnostic ia',
      'ai diagnosis',
      'symptomes',
      'panne',
      'assistant',
      'moteur',
      'engine',
      'ia',
      'ai',
      'recommandation',
    ],
    navTarget: 'diagnostic.index',
    planFlag: 'canUseAI',
  },
  {
    id: 'spare-parts-identify',
    title: {
      en: 'Spare parts identification and repair list',
      fr: 'Identification des pièces détachées et liste de réparation',
    },
    body: {
      en: 'The Spare parts page (/spare-parts) guides you from "I do not know the name of this part" to an orderable reference. Starting from the registered engine (brand, model code, serial number), you pick a functional assembly (carburetor, ignition, lower unit, seawater circuit…) among 21 assemblies matched to the motorization family, follow retailer exploded-view links, and build a repair cart with quantities and references. Known references from the sourced database are pre-filled with their source displayed; the cart exports to CSV.',
      fr: 'La page Pièces détachées (/spare-parts) vous mène de « je ne connais pas le nom de cette pièce » à une référence commandable. À partir du moteur enregistré (marque, code modèle, numéro de série), vous choisissez un ensemble fonctionnel (carburateur, allumage, embase, circuit eau de mer…) parmi 21 ensembles adaptés à la famille de motorisation, suivez les liens vers les vues éclatées des revendeurs et constituez une liste de réparation avec quantités et références. Les références connues de la base sourcée sont pré-remplies avec leur source affichée ; la liste s’exporte en CSV.',
    },
    keywords: [
      'pieces detachees',
      'spare parts',
      'reference',
      'panier',
      'cart',
      'vue eclatee',
      'exploded view',
      'turbine',
      'stock',
      'commander',
    ],
    navTarget: 'spareParts.index',
  },
  {
    id: 'spare-parts-chat',
    title: {
      en: 'AI part reference finder chat',
      fr: 'Chat IA de recherche de références de pièces',
    },
    body: {
      en: 'On plans with AI, a conversational assistant finds part references from your engine serial number. It works in two phases: it first identifies the exact engine model using the serial number and the brand plate pattern, then maps the part you describe onto the parts catalog filtered by motorization family. Displayed references come exclusively from the sourced reference database — the AI never invents part numbers; without a known reference you get the retailer links fallback. Adding to the repair cart pre-fills the reference.',
      fr: 'Sur les plans avec IA, un assistant conversationnel retrouve des références de pièces à partir du numéro de série de votre moteur. Il travaille en deux phases : identifier d’abord le modèle exact du moteur via le numéro de série et le motif de plaque de la marque, puis rapprocher la pièce décrite du catalogue filtré par famille de motorisation. Les références affichées proviennent exclusivement de la base sourcée — l’IA n’invente jamais de numéro ; sans référence connue, vous obtenez le repli vers les liens revendeurs. L’ajout au panier pré-remplit la référence.',
    },
    keywords: [
      'chat pieces',
      'part finder',
      'numero de serie',
      'serial number',
      'reference',
      'ia',
      'ai',
      'plaque',
      'plate',
      'conversationnel',
    ],
    navTarget: 'spareParts.index',
    planFlag: 'canUseAI',
  },
  {
    id: 'safety-division240',
    title: {
      en: 'Division 240 safety equipment compliance',
      fr: 'Conformité de l’armement Division 240',
    },
    body: {
      en: 'FleetAi checks the safety inventory of a boat against the French Division 240 requirements for the declared armament zone (basic ≤ 2 NM, coastal ≤ 6 NM, semi-offshore ≤ 60 NM, offshore beyond). The compliance panel, on the Equipment tab under the Safety filter, flags missing equipment, insufficient quantities (life jackets vs max persons) and expired or due-for-service items, with a percentage score. Each missing line opens a pre-filled add form. It is an aid only: nothing is blocked, and it does not replace the official text or an inspection.',
      fr: 'FleetAi confronte l’inventaire de sécurité d’un bateau aux exigences de la Division 240 pour la zone d’armement déclarée (basique ≤ 2 milles, côtier ≤ 6, semi-hauturier ≤ 60, hauturier au-delà). Le panneau de conformité, dans l’onglet Équipements sous le filtre Sécurité, signale les équipements absents, les quantités insuffisantes (gilets vs personnes max) et les équipements périmés ou à réviser, avec un score en pourcentage. Chaque ligne manquante ouvre un formulaire d’ajout pré-rempli. C’est une aide au suivi : rien n’est bloqué, et cela ne remplace ni le texte officiel ni un contrôle.',
    },
    keywords: [
      'division 240',
      'armement',
      'securite',
      'safety',
      'conformite',
      'compliance',
      'gilets',
      'fusees',
      'zone',
      'radeau',
    ],
    navTarget: 'boats.index',
  },
  {
    id: 'equipment-actions',
    title: {
      en: 'Equipment actions: buy, replace, repair',
      fr: 'Actions sur équipements : acheter, remplacer, réparer',
    },
    body: {
      en: 'Equipment actions are the to-do list of parts and gear per boat: each action has a type (to buy, to replace, to repair), a status (pending, ordered, done, cancelled), an estimated cost and an actual cost — the actual cost is required to mark an action done. An action can be linked to a specific piece of equipment or created from a degraded equipment card with one click, and rental inspections create pre-filled actions from damage findings. Actions are managed in the boat Equipment tab.',
      fr: 'Les actions sur équipements sont la liste des choses à faire sur le matériel d’un bateau : chaque action a un type (à acheter, à remplacer, à réparer), un statut (en attente, commandé, terminé, annulé), un coût estimé et un coût réel — le coût réel est requis pour passer une action à terminé. Une action peut être liée à un équipement précis, créée en un clic depuis une carte d’équipement dégradé, ou pré-remplie depuis un dommage constaté en état des lieux. Les actions se gèrent dans l’onglet Équipements du bateau.',
    },
    keywords: [
      'actions',
      'acheter',
      'buy',
      'remplacer',
      'replace',
      'reparer',
      'repair',
      'cout',
      'cost',
      'statut',
    ],
    navTarget: 'boats.index',
  },
  {
    id: 'boat-documents',
    title: {
      en: 'Boat administrative documents and expiry alerts',
      fr: 'Documents administratifs du bateau et alertes d’expiration',
    },
    body: {
      en: 'Each boat keeps its administrative documents: registration (francisation), insurance, navigation permit, radio license, safety inspection, tonnage, CE certificate, crew role or custom types. A document carries a reference number, issue and expiry dates, issuer, cost and an attached file. FleetAi computes a status per document — valid, expiring soon or expired — and expiring documents trigger notifications so renewals are never missed. Documents live in the Documents tab of the boat page.',
      fr: 'Chaque bateau conserve ses documents administratifs : acte de francisation, assurance, permis de navigation, licence radio, visite de sécurité, jauge, certificat CE, rôle d’équipage ou types personnalisés. Un document porte un numéro de référence, des dates d’émission et d’expiration, un émetteur, un coût et un fichier joint. FleetAi calcule un statut par document — valide, expire bientôt ou expiré — et les documents proches de l’échéance déclenchent des notifications pour ne jamais manquer un renouvellement. Ils vivent dans l’onglet Documents de la fiche bateau.',
    },
    keywords: [
      'documents',
      'assurance',
      'insurance',
      'francisation',
      'permis',
      'licence radio',
      'expiration',
      'expiry',
      'renouvellement',
      'alerte',
    ],
    navTarget: 'boats.index',
  },
  {
    id: 'boat-budget',
    title: {
      en: 'Boat budget tracking',
      fr: 'Suivi du budget par bateau',
    },
    body: {
      en: 'Each boat has a budget page (/boats/:id/budget) that consolidates spending for a chosen year: maintenance costs from the history, fuel costs from refuelings, document costs, port stays with their fees, and free budget entries you add in categories (maintenance, fuel, documents, port, equipment, other). The page shows yearly totals and a monthly breakdown, so you know exactly what each boat costs. Port stays are recorded with the port, the period and the price.',
      fr: 'Chaque bateau dispose d’une page budget (/boats/:id/budget) qui consolide les dépenses d’une année choisie : coûts d’entretien issus de l’historique, carburant issu des avitaillements, coûts des documents, escales portuaires avec leurs frais, et dépenses libres que vous ajoutez par catégorie (entretien, carburant, documents, port, équipement, autre). La page affiche les totaux annuels et la répartition mensuelle, pour savoir précisément ce que coûte chaque bateau. Les escales sont enregistrées avec le port, la période et le prix.',
    },
    keywords: [
      'budget',
      'depenses',
      'expenses',
      'couts',
      'costs',
      'escales',
      'port stays',
      'annuel',
      'mensuel',
      'suivi',
    ],
    navTarget: 'boats.index',
  },
  {
    id: 'ports-management',
    title: {
      en: 'Ports management',
      fr: 'Gestion des ports',
    },
    body: {
      en: 'The Ports page (/ports) lets Pro and Enterprise organizations manage their ports: name, city, country, address and notes, with a detail page per port. Creating, editing and deleting a port is reserved to organization admins; every member can view. Ports feed the rest of the app: they are suggested when entering a home port, a departure or arrival port in the logbook, or a port stay in the budget — those fields remain free text, the list only assists input. Starter plans do not include marina mapping.',
      fr: 'La page Ports (/ports) permet aux organisations Pro et Entreprise de gérer leurs ports : nom, ville, pays, adresse et notes, avec une page de détail par port. Créer, modifier et supprimer un port est réservé aux admins de l’organisation ; tout membre peut consulter. Les ports alimentent le reste de l’app : ils sont suggérés à la saisie d’un port d’attache, d’un port de départ ou d’arrivée dans le journal de bord, ou d’une escale dans le budget — ces champs restent en texte libre, la liste ne fait qu’assister la saisie. Le plan Starter n’inclut pas la cartographie marina.',
    },
    keywords: [
      'port',
      'ports',
      'marina',
      'ville',
      'city',
      'pays',
      'country',
      'gestion',
      'harbour',
      'harbor',
    ],
    navTarget: 'ports.index',
    planFlag: 'canManagePorts',
  },
  {
    id: 'marina-map',
    title: {
      en: 'Marina map: pontoons, moorings and berths',
      fr: 'Plan de marina : pontons, mouillages et places',
    },
    body: {
      en: 'Inside a port, Pro and Enterprise organizations map the marina: pontoons and mooring areas are created with their positions on an interactive 2D plan, and each carries berths (spots) where boats can be assigned. Positions are adjusted by drag on the plan and saved instantly. Creating, editing and deleting pontoons, moorings and their positions is reserved to admins; berths can be created and edited by members. The map gives a visual overview of where every boat of the organization is berthed.',
      fr: 'À l’intérieur d’un port, les organisations Pro et Entreprise cartographient la marina : les pontons et les zones de mouillage sont créés avec leur position sur un plan 2D interactif, et chacun porte des places (spots) où affecter des bateaux. Les positions s’ajustent par glisser-déposer sur le plan et sont enregistrées immédiatement. Créer, modifier et supprimer pontons, mouillages et positions est réservé aux admins ; les places peuvent être créées et modifiées par les membres. Le plan donne une vue visuelle de l’emplacement de chaque bateau de l’organisation.',
    },
    keywords: [
      'ponton',
      'pontoons',
      'mouillage',
      'mooring',
      'place',
      'places',
      'berth',
      'spot',
      'plan',
      'carte',
      'map',
    ],
    navTarget: 'ports.index',
    planFlag: 'canManagePorts',
  },
  {
    id: 'navigation-logbook',
    title: {
      en: 'Logbook: trips',
      fr: 'Journal de bord : les sorties',
    },
    body: {
      en: 'The logbook records the trips of each boat: departure and arrival times and ports, distance in nautical miles, engine hours at start and end, fuel consumed, wind force (Beaufort), sea state, crew on board with roles, and notes. Only one trip can be in progress per boat, and a trip is closed manually — never by timeout, since a trip can span several days. Closing propagates the engine hours to the engine. The fleet-wide logbook (/navigation/logbook) shows statistics and all trips, and trips export to CSV per boat.',
      fr: 'Le journal de bord enregistre les sorties de chaque bateau : dates et ports de départ et d’arrivée, distance en milles, heures moteur au départ et à l’arrivée, carburant consommé, force du vent (Beaufort), état de la mer, équipage à bord avec rôles, et notes. Une seule sortie peut être en cours par bateau, et la clôture est toujours manuelle — jamais par expiration, une sortie pouvant durer plusieurs jours. La clôture propage les heures moteur sur le moteur. La vue flotte (/navigation/logbook) montre statistiques et sorties, exportables en CSV par bateau.',
    },
    keywords: [
      'journal de bord',
      'logbook',
      'sortie',
      'sorties',
      'trip',
      'trips',
      'navigation',
      'distance',
      'beaufort',
      'cloture',
    ],
    navTarget: 'navigation.logbook',
  },
  {
    id: 'navigation-log-points',
    title: {
      en: 'Log points with automatic GPS course and speed',
      fr: 'Points de log avec cap et vitesse GPS automatiques',
    },
    body: {
      en: 'During a trip, you record log points with a single tap from the boat page: a short GPS burst (a few seconds of fixes) computes the position, course over ground and speed over ground automatically, and you add the sail configuration and a comment by hand. A point without GPS remains possible. The trip detail page shows the chronological list of points and the track drawn on a map. Points can be added offline at sea and are synchronized with their real timestamp when the connection returns.',
      fr: 'Pendant une sortie, vous consignez des points de log d’un simple tap depuis la fiche bateau : une courte rafale GPS (quelques secondes de mesures) calcule automatiquement la position, le cap fond et la vitesse fond, et vous ajoutez à la main la configuration de voiles et un commentaire. Un point sans GPS reste possible. La page de détail de la sortie affiche la liste chronologique des points et le tracé sur une carte. Les points peuvent être ajoutés hors-ligne en mer et sont synchronisés avec leur horodatage réel au retour de la connexion.',
    },
    keywords: [
      'point de log',
      'log point',
      'gps',
      'cap',
      'cog',
      'vitesse',
      'sog',
      'trace',
      'track',
      'carte',
      'position',
    ],
    navTarget: 'navigation.logbook',
  },
  {
    id: 'fuel-logs',
    title: {
      en: 'Fuel logs (refuelings)',
      fr: 'Avitaillements en carburant',
    },
    body: {
      en: 'Fuel logs record every refueling of a boat: date, quantity in liters, price per liter and total cost, engine hours at fueling, fuel type (diesel, petrol, electric, other), supplier and notes, optionally linked to a specific engine. The fleet fuel page (/navigation/fuel) aggregates refuelings across boats, fuel costs feed the boat budget, and refuelings export to CSV per boat. Entries can be recorded offline and synchronized later — useful at the fuel dock without signal.',
      fr: 'Les avitaillements enregistrent chaque plein d’un bateau : date, quantité en litres, prix au litre et coût total, heures moteur au moment du plein, type de carburant (diesel, essence, électrique, autre), fournisseur et notes, avec rattachement optionnel à un moteur précis. La page carburant flotte (/navigation/fuel) agrège les pleins de tous les bateaux, les coûts alimentent le budget du bateau, et les avitaillements s’exportent en CSV par bateau. La saisie fonctionne hors-ligne avec synchronisation ultérieure — utile au ponton carburant sans réseau.',
    },
    keywords: [
      'carburant',
      'fuel',
      'avitaillement',
      'plein',
      'refueling',
      'litres',
      'liters',
      'prix',
      'diesel',
      'essence',
    ],
    navTarget: 'navigation.fuel',
  },
  {
    id: 'incidents',
    title: {
      en: 'Incident tracking',
      fr: 'Suivi des incidents',
    },
    body: {
      en: 'Incidents record what went wrong at sea or in port: grounding, flooding, rigging failure, engine failure, collision, fire, theft or vandalism, or other. Each incident carries a date, a location, a description, a status (open, in progress, closed) and insurance claim tracking (claimed flag and claim reference). The fleet incidents page (/navigation/incidents) lists incidents across all boats, and each boat page has its own incidents view. Deleting an incident is reserved to admins.',
      fr: 'Les incidents consignent ce qui a mal tourné en mer ou au port : échouement, voie d’eau, avarie de gréement, panne moteur, collision, incendie, vol ou vandalisme, ou autre. Chaque incident porte une date, un lieu, une description, un statut (ouvert, en cours, clos) et le suivi assurance (déclaration et référence de dossier). La page incidents flotte (/navigation/incidents) liste les incidents de tous les bateaux, et chaque fiche bateau a sa propre vue. La suppression d’un incident est réservée aux admins.',
    },
    keywords: [
      'incident',
      'incidents',
      'avarie',
      'panne',
      'collision',
      'echouement',
      'grounding',
      'assurance',
      'insurance',
      'sinistre',
    ],
    navTarget: 'navigation.incidents',
  },
  {
    id: 'crew-management',
    title: {
      en: 'Crew members and certifications',
      fr: 'Équipiers et certifications',
    },
    body: {
      en: 'The Crew page (/crew) manages the crew members of the organization: contact details, notes, and their certifications — coastal or offshore permit, VHF, CRR, STCW, medical certificate, first aid and more, each with a reference number and expiry date. Badges show valid, expiring or expired certifications, and typical validity durations are suggested. Crew members are attached to logbook trips with a role (skipper, crew, passenger), and a regulatory crew role PDF can be downloaded per trip.',
      fr: 'La page Équipiers (/crew) gère les équipiers de l’organisation : coordonnées, notes et certifications — permis côtier ou hauturier, VHF, CRR, STCW, visite médicale, premiers secours et autres, chacune avec numéro de référence et date d’expiration. Des badges signalent les certifications valides, bientôt expirées ou expirées, et des durées de validité types sont suggérées. Les équipiers sont rattachés aux sorties du journal de bord avec un rôle (skipper, équipier, passager), et un rôle d’équipage réglementaire en PDF se télécharge par sortie.',
    },
    keywords: [
      'equipier',
      'equipiers',
      'crew',
      'certification',
      'permis',
      'permit',
      'vhf',
      'stcw',
      'skipper',
      'role d equipage',
    ],
    navTarget: 'crew.index',
  },
  {
    id: 'reservations',
    title: {
      en: 'Boat reservations',
      fr: 'Réservations de bateaux',
    },
    body: {
      en: 'Reservations manage charter bookings per boat: a period with times, a client (free text or linked to a CRM client), a status (option, confirmed, cancelled) and a total price. Double-booking is prevented: an option is blocked by any overlapping non-cancelled reservation, and confirming a reservation auto-cancels overlapping options. A service type can be set: bareboat, skippered, day charter, cabin or other. Each boat has a calendar and list view, and the fleet page (/reservations) shows a read-only timeline with filters.',
      fr: 'Les réservations gèrent la location par bateau : une période avec horaires, un client (texte libre ou lié à une fiche client CRM), un statut (option, confirmée, annulée) et un prix total. Le double-booking est empêché : une option est bloquée par toute réservation non annulée qui se chevauche, et la confirmation annule automatiquement les options en conflit. Un type de prestation peut être précisé : coque nue, avec skipper, sortie à la journée, à la cabine ou autre. Chaque bateau a son calendrier et sa liste, et la page flotte (/reservations) montre une frise en lecture seule.',
    },
    keywords: [
      'reservation',
      'reservations',
      'location',
      'charter',
      'booking',
      'option',
      'confirmee',
      'calendrier',
      'double booking',
      'prestation',
    ],
    navTarget: 'reservations.index',
    planFlag: 'canManageReservations',
  },
  {
    id: 'reservation-pricing',
    title: {
      en: 'Pricing and seasonal rates',
      fr: 'Tarifs et périodes saisonnières',
    },
    body: {
      en: 'Pricing defines what a boat rental costs: a base daily price, an optional weekly price, a deposit, minimum and maximum durations, and a currency, set in the Pricing tab of the boat page. Seasonal periods — global to the organization or specific to a boat — adjust the nightly rate with an absolute price or a multiplier, with priorities to settle overlaps. The reservation form computes the quote live, pre-fills the total (which stays editable) and enforces the duration bounds. Seasons are managed on the /pricing/seasons page.',
      fr: 'La tarification définit le prix de location d’un bateau : tarif journalier de base, tarif hebdomadaire optionnel, caution, durées minimale et maximale et devise, réglés dans l’onglet Tarif de la fiche bateau. Des périodes saisonnières — globales à l’organisation ou propres à un bateau — ajustent le prix par nuit avec un prix absolu ou un coefficient, avec des priorités pour départager les chevauchements. Le formulaire de réservation calcule le devis en direct, pré-remplit le total (qui reste modifiable) et fait respecter les bornes de durée. Les saisons se gèrent sur /pricing/seasons.',
    },
    keywords: [
      'tarif',
      'tarifs',
      'pricing',
      'prix',
      'saison',
      'saisons',
      'seasonal',
      'caution',
      'deposit',
      'devis',
      'quote',
    ],
    navTarget: 'reservations.index',
    planFlag: 'canManagePricing',
  },
  {
    id: 'inspections',
    title: {
      en: 'Check-out and check-in inspections',
      fr: 'États des lieux de départ et de retour',
    },
    body: {
      en: 'Inspections record the condition of a boat at the start (check-out) and end (check-in) of a reservation — at most one of each per reservation, shown side by side. A structured checklist, filtered by boat category, lets you mark each point ok, remark or damage (a note is required beyond ok); at check-in, each point shows its check-out state and any degradation is highlighted. A damage point can create a pre-filled equipment action, photos can be attached, and an inspection can even be created offline on the pontoon.',
      fr: 'Les états des lieux constatent l’état du bateau au départ (check-out) et au retour (check-in) d’une réservation — au plus un de chaque par réservation, affichés côte à côte. Une checklist structurée, filtrée selon la catégorie du bateau, permet de marquer chaque point ok, remarque ou dommage (une note est requise au-delà de ok) ; au retour, chaque point affiche son état au départ et toute dégradation est mise en évidence. Un dommage peut créer une action d’équipement pré-remplie, des photos s’attachent, et un état des lieux peut même se créer hors-ligne sur le ponton.',
    },
    keywords: [
      'etat des lieux',
      'inspection',
      'check-out',
      'check-in',
      'checklist',
      'dommage',
      'damage',
      'constat',
      'location',
      'photos',
    ],
    navTarget: 'reservations.index',
    planFlag: 'canManageReservations',
  },
  {
    id: 'rental-contracts',
    title: {
      en: 'Rental contracts',
      fr: 'Contrats de location',
    },
    body: {
      en: 'Each reservation can carry a rental contract, managed from the reservation. The contract goes through three statuses: draft, sent and signed. FleetAi generates the contract as a PDF from the reservation and client data, lets you send it, and stores the signed document you upload once the client has signed — the reservation then shows the contract state and gives access to both the generated PDF and the signed file. Deleting a contract is reserved to admins; creation and edition are open to members.',
      fr: 'Chaque réservation peut porter un contrat de location, géré depuis la réservation. Le contrat passe par trois statuts : brouillon, envoyé et signé. FleetAi génère le contrat en PDF à partir des données de la réservation et du client, permet de l’envoyer, puis conserve le document signé que vous téléversez une fois la signature obtenue — la réservation affiche alors l’état du contrat et donne accès au PDF généré comme au fichier signé. La suppression d’un contrat est réservée aux admins ; la création et l’édition sont ouvertes aux membres.',
    },
    keywords: [
      'contrat',
      'contrats',
      'contract',
      'location',
      'rental',
      'signature',
      'signe',
      'signed',
      'pdf',
      'brouillon',
    ],
    navTarget: 'reservations.index',
    planFlag: 'canManageReservations',
  },
  {
    id: 'clients-crm',
    title: {
      en: 'Client directory (CRM)',
      fr: 'Répertoire clients (CRM)',
    },
    body: {
      en: 'The Clients page (/clients) is a light CRM per organization: contact details, address, navigation permit type and number, free notes, documents (permits, ID…) and a status — active, inactive or blacklisted. A blacklisted client is refused on any reservation, at creation and update. A reservation can be linked to a client record, and the client page shows the full reservation history. Linked quotes and invoices resolve the client automatically. Deleting a client is admin-only and unlinks reservations while keeping their text snapshot.',
      fr: 'La page Clients (/clients) est un CRM léger par organisation : coordonnées, adresse, type et numéro de permis de navigation, notes libres, documents (permis, identité…) et un statut — actif, inactif ou blacklisté. Un client blacklisté est refusé sur toute réservation, à la création comme à la modification. Une réservation peut être rattachée à une fiche client, et la fiche affiche tout l’historique des réservations. Les devis et factures liés résolvent le client automatiquement. La suppression d’un client est réservée aux admins et délie les réservations en conservant leur snapshot texte.',
    },
    keywords: [
      'client',
      'clients',
      'crm',
      'repertoire',
      'directory',
      'blacklist',
      'fiche client',
      'historique',
      'permis',
      'contacts',
    ],
    navTarget: 'clients.index',
    planFlag: 'canManageClients',
  },
  {
    id: 'clients-gdpr',
    title: {
      en: 'Client GDPR: consent, anonymization, data export',
      fr: 'RGPD clients : consentement, anonymisation, export',
    },
    body: {
      en: 'The client CRM includes GDPR tooling. A consent checkbox timestamps the first consent on the record. The right to erasure is handled by anonymization: personal data is replaced, documents are deleted, linked reservations keep an anonymized snapshot, and the record is permanently frozen — it can no longer be edited and shows an Anonymized badge. Anonymization is admin-only and irreversible. For data portability, each client record exports as a JSON file containing the client, the reservation history and document metadata.',
      fr: 'Le CRM clients embarque les outils RGPD. Une case de consentement horodate le premier consentement sur la fiche. Le droit à l’effacement passe par l’anonymisation : les données personnelles sont remplacées, les documents supprimés, les réservations liées gardent un snapshot anonymisé, et la fiche est définitivement gelée — elle n’est plus modifiable et porte un badge Anonymisé. L’anonymisation est réservée aux admins et irréversible. Pour la portabilité, chaque fiche s’exporte en JSON avec le client, l’historique des réservations et les métadonnées des documents.',
    },
    keywords: [
      'rgpd',
      'gdpr',
      'consentement',
      'consent',
      'anonymisation',
      'anonymization',
      'effacement',
      'erasure',
      'export',
      'portabilite',
    ],
    navTarget: 'clients.index',
    planFlag: 'canManageClients',
  },
  {
    id: 'invoices-quotes',
    title: {
      en: 'Quotes and invoices',
      fr: 'Devis et factures',
    },
    body: {
      en: 'The Invoices page (/invoices) manages quotes and invoices per organization: multi-line documents with quantity and unit price per line, a single VAT rate, and totals always recomputed server-side. Numbering is sequential and gapless per organization and type — DEV-000001 for quotes, FAC-000001 for invoices, two independent sequences. A document can be linked to a client record and a reservation, and a pre-filled quote can be created from a reservation in one click. Deleting a document is admin-only.',
      fr: 'La page Factures (/invoices) gère devis et factures par organisation : documents multi-lignes avec quantité et prix unitaire par ligne, un taux de TVA unique, et des totaux toujours recalculés côté serveur. La numérotation est séquentielle et sans trou par organisation et par type — DEV-000001 pour les devis, FAC-000001 pour les factures, deux séquences indépendantes. Un document peut être lié à une fiche client et à une réservation, et un devis pré-rempli se crée depuis une réservation en un clic. La suppression d’un document est réservée aux admins.',
    },
    keywords: [
      'facture',
      'factures',
      'invoice',
      'invoices',
      'devis',
      'quote',
      'tva',
      'vat',
      'numerotation',
      'lignes',
    ],
    navTarget: 'invoices.index',
    planFlag: 'canManageInvoices',
  },
  {
    id: 'invoice-lifecycle',
    title: {
      en: 'Invoice lifecycle: send, convert, pay, overdue',
      fr: 'Cycle de vie des factures : envoi, conversion, paiement, retard',
    },
    body: {
      en: 'Documents follow a lifecycle: draft, sent, paid, with overdue and cancelled as transverse states. Sending emails the document to the client with the branded PDF attached and moves it from draft to sent (refused if the client has no email). A quote converts once into a new draft invoice that copies client, reservation, lines and VAT. Marking paid timestamps the payment. A daily job automatically flags sent, unpaid invoices past their due date as overdue. The PDF is downloadable at any time, branded with your white-label when enabled.',
      fr: 'Les documents suivent un cycle de vie : brouillon, envoyé, payé, avec retard et annulé comme états transverses. L’envoi expédie le document par email au client avec le PDF en pièce jointe et le passe de brouillon à envoyé (refusé si le client n’a pas d’email). Un devis se convertit une seule fois en une nouvelle facture brouillon reprenant client, réservation, lignes et TVA. Marquer payé horodate le paiement. Un traitement quotidien passe automatiquement en retard les factures envoyées, impayées et échues. Le PDF se télécharge à tout moment, aux couleurs de votre marque blanche si activée.',
    },
    keywords: [
      'envoi',
      'send',
      'conversion',
      'convert',
      'payee',
      'paid',
      'retard',
      'overdue',
      'pdf',
      'email',
      'cycle',
    ],
    navTarget: 'invoices.index',
    planFlag: 'canManageInvoices',
  },
  {
    id: 'members-roles',
    title: {
      en: 'Members, roles and invitations',
      fr: 'Membres, rôles et invitations',
    },
    body: {
      en: 'The Members settings (/settings/members) manage who accesses the organization. Four roles exist: admin (everything, including deletions and settings), member (day-to-day work without deletions), mechanic (restricted to the maintenance module across the whole organization) and boat_owner (read-only self-service portal limited to their own boats). New people join by email invitation; inviting a boat owner requires selecting the boats they own. The last admin of an organization can never be demoted or removed.',
      fr: 'Les réglages Membres (/settings/members) gèrent qui accède à l’organisation. Quatre rôles existent : admin (tout, y compris suppressions et réglages), membre (le travail quotidien sans les suppressions), mécanicien (restreint au module maintenance sur toute l’organisation) et propriétaire de bateau (portail self-service en lecture seule limité à ses propres bateaux). L’arrivée passe par une invitation par email ; inviter un propriétaire demande de sélectionner ses bateaux. Le dernier admin d’une organisation ne peut jamais être rétrogradé ni supprimé.',
    },
    keywords: [
      'membres',
      'members',
      'roles',
      'admin',
      'member',
      'mecanicien',
      'mechanic',
      'proprietaire',
      'invitation',
      'permissions',
    ],
    navTarget: 'settings.members',
  },
  {
    id: 'owner-portal',
    title: {
      en: 'Boat owner portal',
      fr: 'Portail propriétaire',
    },
    body: {
      en: 'Users with the boat_owner role get a dedicated read-only portal at /owner/boats, listing only the boats they own — co-ownership is supported, a boat can have several owners. The portal shows each boat with its maintenance, its reservations and the invoices linked to those reservations, without any access to the staff pages of the organization. Owners are invited by an admin from the Members settings, selecting which boats they own; admins also manage co-owners from the boat edit page.',
      fr: 'Les utilisateurs au rôle propriétaire de bateau disposent d’un portail dédié en lecture seule sur /owner/boats, qui liste uniquement les bateaux qu’ils possèdent — la copropriété est gérée, un bateau peut avoir plusieurs propriétaires. Le portail montre chaque bateau avec sa maintenance, ses réservations et les factures liées à ces réservations, sans aucun accès aux pages staff de l’organisation. Les propriétaires sont invités par un admin depuis les réglages Membres, en sélectionnant leurs bateaux ; les copropriétaires se gèrent depuis l’édition du bateau.',
    },
    keywords: [
      'portail',
      'portal',
      'proprietaire',
      'owner',
      'boat owner',
      'lecture seule',
      'read only',
      'copropriete',
      'co-ownership',
      'self-service',
    ],
    navTarget: null,
  },
  {
    id: 'plans-overview',
    title: {
      en: 'Plans: Starter, Pro, Enterprise',
      fr: 'Plans : Starter, Pro, Entreprise',
    },
    body: {
      en: 'FleetAi has three plans. Starter is free: 2 boats, 1 member, 1 GB storage, no AI, no export. Pro costs 20 €/month (16 € billed annually): 8 boats, 5 members, 20 GB, AI with 1 million tokens per month, CSV export, task grouping, marina mapping and a 90-day audit log. Enterprise costs 99 €/month (79 € billed annually): unlimited boats, members and storage, unlimited AI tokens, all modules included (CRM, invoicing, reservations, pricing), AI customization and white-label. Manage your subscription in Settings, Billing.',
      fr: 'FleetAi propose trois plans. Starter est gratuit : 2 bateaux, 1 membre, 1 Go de stockage, sans IA ni export. Pro coûte 20 €/mois (16 € en facturation annuelle) : 8 bateaux, 5 membres, 20 Go, IA avec 1 million de tokens par mois, export CSV, regroupement de tâches, cartographie marina et journal d’audit 90 jours. Entreprise coûte 99 €/mois (79 € en annuel) : bateaux, membres et stockage illimités, tokens IA illimités, tous les modules inclus (CRM, facturation, réservations, tarifs), personnalisation IA et marque blanche. Gérez votre abonnement dans Réglages, Facturation.',
    },
    keywords: [
      'plan',
      'plans',
      'starter',
      'pro',
      'entreprise',
      'enterprise',
      'prix',
      'pricing',
      'abonnement',
      'subscription',
      'upgrade',
    ],
    navTarget: 'settings.billing',
  },
  {
    id: 'modules-addons',
    title: {
      en: 'Modules and add-ons on the Pro plan',
      fr: 'Modules et add-ons sur le plan Pro',
    },
    body: {
      en: 'On the Pro plan, two modules can be subscribed à la carte for 15 €/month each (12 € billed annually). The Charter module unlocks reservations management, inspections, rental contracts and per-boat pricing with seasons. The CRM & Invoicing module unlocks the client directory and quotes/invoices. The Enterprise plan includes both. A quantitative add-on, Extra boats, raises the Pro boat quota by one boat per unit for 4 €/month each. Modules and add-ons are managed from Settings, Billing; a module granted manually shows its origin.',
      fr: 'Sur le plan Pro, deux modules se souscrivent à la carte pour 15 €/mois chacun (12 € en annuel). Le module Location débloque la gestion des réservations, les états des lieux, les contrats de location et la tarification par bateau avec saisons. Le module CRM & Facturation débloque le répertoire clients et les devis/factures. Le plan Entreprise inclut les deux. Un add-on quantitatif, Bateaux supplémentaires, relève le quota de bateaux Pro d’un bateau par unité pour 4 €/mois chacune. Modules et add-ons se gèrent dans Réglages, Facturation ; un module offert affiche son origine.',
    },
    keywords: [
      'module',
      'modules',
      'addon',
      'add-on',
      'charter',
      'location',
      'crm',
      'facturation',
      'bateaux supplementaires',
      'extra boats',
      'a la carte',
    ],
    navTarget: 'settings.billing',
  },
  {
    id: 'ai-token-quota',
    title: {
      en: 'Monthly AI token quota',
      fr: 'Quota mensuel de tokens IA',
    },
    body: {
      en: 'AI usage is metered in tokens per organization and per month. The Pro plan includes 1,000,000 tokens per month; Enterprise is unlimited; Starter has no AI access at all. A usage gauge is shown in Settings, Billing, and admins receive an email when 80% then 100% of the quota is reached. Once the limit is hit, AI features pause until the counter resets on the 1st of the month. Organizations using their own API key (BYOK) for the copilot bypass the quota — usage is still recorded for statistics.',
      fr: 'L’usage de l’IA est mesuré en tokens par organisation et par mois. Le plan Pro inclut 1 000 000 de tokens par mois ; Entreprise est illimité ; Starter n’a pas accès à l’IA. Une jauge de consommation s’affiche dans Réglages, Facturation, et les admins reçoivent un email au franchissement de 80 % puis de 100 % du quota. Une fois la limite atteinte, les fonctions IA sont en pause jusqu’à la remise à zéro du compteur le 1er du mois. Les organisations qui utilisent leur propre clé API (BYOK) pour le copilote contournent le quota — l’usage reste enregistré pour les statistiques.',
    },
    keywords: [
      'quota',
      'tokens',
      'token',
      'ia',
      'ai',
      'limite',
      'limit',
      'mensuel',
      'monthly',
      'consommation',
      'usage',
    ],
    navTarget: 'settings.billing',
  },
  {
    id: 'settings-ai-byok',
    title: {
      en: 'AI settings: bring your own API key (BYOK)',
      fr: 'Réglages IA : votre propre clé API (BYOK)',
    },
    body: {
      en: 'From the Pro plan, the AI settings (/settings/ai) let admins register one API key per provider — Mistral, Claude (Anthropic), ChatGPT (OpenAI) and Gemini (Google) — then choose the active provider used by the FleetAi copilot. Keys are stored encrypted and never displayed again; only a configured flag is shown. With an active BYOK provider, copilot calls run on your own account and skip the monthly token quota. Removing the active key returns the organization to the app default (Mistral). Other AI features stay on the app key.',
      fr: 'Dès le plan Pro, les réglages IA (/settings/ai) permettent aux admins d’enregistrer une clé API par fournisseur — Mistral, Claude (Anthropic), ChatGPT (OpenAI) et Gemini (Google) — puis de choisir le fournisseur actif utilisé par le copilote FleetAi. Les clés sont chiffrées et jamais réaffichées ; seul un indicateur configuré apparaît. Avec un fournisseur actif en BYOK, les appels du copilote passent sur votre propre compte et sautent le quota mensuel de tokens. Supprimer la clé active ramène l’organisation au défaut de l’app (Mistral). Les autres fonctions IA restent sur la clé de l’app.',
    },
    keywords: [
      'byok',
      'cle api',
      'api key',
      'mistral',
      'claude',
      'chatgpt',
      'gemini',
      'fournisseur',
      'provider',
      'reglages ia',
    ],
    navTarget: 'settings.ai',
    planFlag: 'canUseAI',
  },
  {
    id: 'ai-customization',
    title: {
      en: 'AI customization: business prompt and model',
      fr: 'Personnalisation IA : prompt métier et modèle',
    },
    body: {
      en: 'On the Enterprise plan, admins can customize the AI in Settings, AI customization (/settings/ai): a custom system prompt of up to 2,000 characters injects your business context (fleet specifics, internal procedures, vocabulary) before every AI request of the organization — fleet analysis, boat suggestions and chat alike — and a model override picks the model used among those of the active provider. Both are optional and revert to defaults when cleared. On Pro, AI itself is included but this customization is not.',
      fr: 'Sur le plan Entreprise, les admins personnalisent l’IA dans Réglages, Personnalisation IA (/settings/ai) : un prompt système personnalisé de 2 000 caractères maximum injecte votre contexte métier (spécificités de flotte, procédures internes, vocabulaire) avant chaque requête IA de l’organisation — analyse de flotte, suggestions bateau et chat compris — et un choix de modèle remplace le modèle par défaut parmi ceux du fournisseur actif. Les deux sont facultatifs et reviennent aux défauts une fois effacés. Sur Pro, l’IA est incluse mais pas cette personnalisation.',
    },
    keywords: [
      'personnalisation',
      'customization',
      'prompt',
      'systeme',
      'system prompt',
      'modele',
      'model',
      'contexte metier',
      'entreprise',
      'enterprise',
    ],
    navTarget: 'settings.ai',
    planFlag: 'canCustomizeAI',
  },
  {
    id: 'ai-suggestions',
    title: {
      en: 'Proactive AI suggestions and fleet analysis',
      fr: 'Suggestions IA proactives et analyse de flotte',
    },
    body: {
      en: 'On plans with AI, FleetAi generates maintenance suggestions from your real data: a fleet analysis launched from the dashboard, plus per-boat and per-engine suggestion panels. A daily scheduled job also regenerates suggestions proactively when the underlying data changed (engines, hours, tasks, events, safety equipment), at most once a week per boat, and notifies admins when new suggestions are ready. Suggestions are generated in your language and take into account the standard operation intervals of each engine family.',
      fr: 'Sur les plans avec IA, FleetAi génère des suggestions d’entretien à partir de vos données réelles : une analyse de flotte lancée depuis le tableau de bord, plus des panneaux de suggestions par bateau et par moteur. Un traitement planifié quotidien régénère aussi les suggestions de manière proactive quand les données sous-jacentes ont changé (moteurs, heures, tâches, événements, équipements de sécurité), au plus une fois par semaine par bateau, et notifie les admins quand de nouvelles suggestions sont prêtes. Les suggestions sont générées dans votre langue et tiennent compte des intervalles standard de chaque famille moteur.',
    },
    keywords: [
      'suggestions',
      'analyse',
      'analysis',
      'ia',
      'ai',
      'proactif',
      'proactive',
      'flotte',
      'fleet',
      'recommandations',
    ],
    navTarget: 'dashboard',
    planFlag: 'canUseAI',
  },
  {
    id: 'assistant-copilot',
    title: {
      en: 'FleetAi copilot (this assistant)',
      fr: 'Copilote FleetAi (cet assistant)',
    },
    body: {
      en: 'The FleetAi copilot is the chat panel pinned at the bottom of the sidebar, available on plans with AI. It answers questions about your fleet by reading your organization data through bounded tools, explains the product, and can propose a maintenance task — never created without your explicit confirmation on a dedicated card. It can also hand you off to the engine diagnostic or the part search chat with the right boat and engine pre-selected, and suggest navigation links to app pages. Each conversation keeps up to 20 of your messages; start a new one anytime.',
      fr: 'Le copilote FleetAi est le panneau de chat épinglé en bas de la barre latérale, disponible sur les plans avec IA. Il répond aux questions sur votre flotte en lisant les données de votre organisation via des outils bornés, explique le produit et peut proposer une tâche de maintenance — jamais créée sans votre confirmation explicite sur une carte dédiée. Il peut aussi vous orienter vers le diagnostic de panne ou la recherche de pièces avec le bon bateau et le bon moteur pré-sélectionnés, et suggérer des liens vers les pages de l’app. Chaque conversation garde jusqu’à 20 de vos messages ; démarrez-en une nouvelle à tout moment.',
    },
    keywords: [
      'copilote',
      'copilot',
      'assistant',
      'chat',
      'fleetai',
      'panneau',
      'questions',
      'aide',
      'help',
      'conversation',
    ],
    navTarget: null,
    planFlag: 'canUseAI',
  },
  {
    id: 'csv-import',
    title: {
      en: 'CSV import',
      fr: 'Import CSV',
    },
    body: {
      en: 'On Pro and Enterprise plans, the Import page (/settings/import) imports maintenance history from a CSV file (semicolon-separated). Required columns are date (YYYY-MM-DD), title and subject; optional ones are notes, engine caption, sail caption and cost. The import always starts with a dry run: the file is parsed and validated line by line, errors are reported with their line numbers, and nothing is written until you confirm. The actual import runs in a transaction — if a line fails, everything is rolled back.',
      fr: 'Sur les plans Pro et Entreprise, la page Import (/settings/import) importe l’historique d’entretien depuis un fichier CSV (séparé par des points-virgules). Les colonnes requises sont la date (AAAA-MM-JJ), le titre et le sujet ; les optionnelles sont les notes, la légende moteur, la légende voile et le coût. L’import commence toujours par un essai à blanc : le fichier est analysé et validé ligne par ligne, les erreurs sont rapportées avec leur numéro de ligne, et rien n’est écrit avant votre confirmation. L’import réel s’exécute en transaction — si une ligne échoue, tout est annulé.',
    },
    keywords: [
      'import',
      'csv',
      'fichier',
      'file',
      'upload',
      'migration',
      'donnees',
      'data',
      'apercu',
      'preview',
    ],
    navTarget: 'settings.import',
    planFlag: 'canExport',
  },
  {
    id: 'csv-pdf-export',
    title: {
      en: 'CSV and PDF exports',
      fr: 'Exports CSV et PDF',
    },
    body: {
      en: 'On Pro and Enterprise plans, each boat exports its data as CSV files: maintenance history (with total cost), fuel logs and logbook trips. Files use UTF-8 with BOM and semicolon separators, so they open cleanly in French Excel. Export links live on the Import/Export settings page and the relevant boat tabs. Beyond CSV, FleetAi also produces PDFs: crew role per trip, quotes and invoices, and the spare-parts repair list exports to CSV too. Client records export as GDPR JSON files.',
      fr: 'Sur les plans Pro et Entreprise, chaque bateau exporte ses données en CSV : historique d’entretien (avec coût total), avitaillements et sorties du journal de bord. Les fichiers sont en UTF-8 avec BOM et séparés par des points-virgules, pour s’ouvrir proprement dans Excel en français. Les liens d’export se trouvent sur la page Import/Export des réglages et sur les onglets concernés du bateau. Au-delà du CSV, FleetAi produit aussi des PDF : rôle d’équipage par sortie, devis et factures, et la liste de réparation de pièces s’exporte aussi en CSV. Les fiches clients s’exportent en JSON RGPD.',
    },
    keywords: [
      'export',
      'csv',
      'pdf',
      'telecharger',
      'download',
      'excel',
      'donnees',
      'data',
      'historique',
      'journal',
    ],
    navTarget: 'settings.import',
    planFlag: 'canExport',
  },
  {
    id: 'offline-pwa',
    title: {
      en: 'Offline mode (PWA)',
      fr: 'Mode hors-ligne (PWA)',
    },
    body: {
      en: 'FleetAi is an installable progressive web app (add it to your phone or desktop home screen). Offline, you can browse recently visited pages and keep entering data at sea: log points, trip creation and closure, refuelings, maintenance sheet items, inspections and damage findings. Entries are stored locally in a queue and synchronized automatically when the connection returns, keeping their real timestamps. If a record changed in the meantime, a conflict dialog lets you resolve it instead of overwriting silently.',
      fr: 'FleetAi est une application web progressive installable (ajoutez-la à l’écran d’accueil de votre téléphone ou ordinateur). Hors-ligne, vous consultez les pages récemment visitées et continuez à saisir en mer : points de log, création et clôture de sortie, avitaillements, items de fiches d’entretien, états des lieux et dommages constatés. Les saisies sont stockées localement dans une file et synchronisées automatiquement au retour de la connexion, en conservant leur horodatage réel. Si un enregistrement a changé entre-temps, une fenêtre de conflit vous laisse arbitrer au lieu d’écraser en silence.',
    },
    keywords: [
      'hors ligne',
      'offline',
      'pwa',
      'installation',
      'install',
      'synchronisation',
      'sync',
      'mer',
      'mobile',
      'file d attente',
      'queue',
    ],
    navTarget: null,
  },
  {
    id: 'notifications',
    title: {
      en: 'Notifications: bell, page and push',
      fr: 'Notifications : cloche, page et push',
    },
    body: {
      en: 'Notifications keep you informed of events in your organization: quota thresholds, plan changes, new members, module deactivation, AI suggestions ready, expiring documents and safety equipment. The bell in the layout shows an unread badge and the five latest; the full paginated list lives at /notifications. Delivery is real time in the open tab, and web push can send field events to your phone even with the app closed — enable it per device in Settings, Notifications. Each notification links to the relevant page.',
      fr: 'Les notifications vous informent des événements de votre organisation : seuils de quota, changements de plan, nouveaux membres, désactivation de module, suggestions IA prêtes, documents et équipements de sécurité qui expirent. La cloche du layout affiche un badge de non-lus et les cinq dernières ; la liste complète paginée vit sur /notifications. La livraison est en temps réel dans l’onglet ouvert, et le push web peut envoyer les événements terrain sur votre téléphone même app fermée — à activer par appareil dans Réglages, Notifications. Chaque notification renvoie vers la page concernée.',
    },
    keywords: [
      'notification',
      'notifications',
      'cloche',
      'bell',
      'push',
      'alertes',
      'alerts',
      'non lus',
      'unread',
      'temps reel',
    ],
    navTarget: 'notifications.index',
  },
  {
    id: 'dark-theme',
    title: {
      en: 'Dark theme',
      fr: 'Thème sombre',
    },
    body: {
      en: 'FleetAi supports a dark theme across the whole app. The preference has three values: system (the default, which follows your operating system setting), light and dark. Change it from your profile settings (Settings, My account): the choice is saved on your account and applied immediately, on every device where you sign in. With the system preference, the interface switches automatically when your OS changes between light and dark mode — no reload needed.',
      fr: 'FleetAi propose un thème sombre sur toute l’application. La préférence a trois valeurs : système (le défaut, qui suit le réglage de votre système d’exploitation), clair et sombre. Modifiez-la depuis vos réglages de profil (Réglages, Mon compte) : le choix est enregistré sur votre compte et appliqué immédiatement, sur chaque appareil où vous vous connectez. Avec la préférence système, l’interface bascule automatiquement quand votre OS passe du mode clair au mode sombre — sans rechargement.',
    },
    keywords: [
      'theme',
      'sombre',
      'dark',
      'clair',
      'light',
      'dark mode',
      'apparence',
      'appearance',
      'systeme',
      'affichage',
    ],
    navTarget: null,
  },
  {
    id: 'language-switch',
    title: {
      en: 'Interface language (French / English)',
      fr: 'Langue de l’interface (français / anglais)',
    },
    body: {
      en: 'FleetAi is fully available in French and English. Your language is a per-user setting, changed from your profile settings and saved on your account. The locale drives the whole experience: interface texts, date and time formats, AI answers and suggestions (generated in your language), and backend documents such as invoice PDFs and emails. Before you pick a language, the app follows your browser preference. Team members can each use their own language within the same organization.',
      fr: 'FleetAi est entièrement disponible en français et en anglais. Votre langue est un réglage individuel, modifié depuis vos réglages de profil et enregistré sur votre compte. La locale pilote toute l’expérience : textes de l’interface, formats de dates et d’heures, réponses et suggestions IA (générées dans votre langue), et documents produits côté serveur comme les PDF de facture et les emails. Avant tout choix, l’app suit la préférence de votre navigateur. Chaque membre d’une même organisation peut utiliser sa propre langue.',
    },
    keywords: [
      'langue',
      'language',
      'francais',
      'french',
      'anglais',
      'english',
      'locale',
      'traduction',
      'translation',
      'i18n',
    ],
    navTarget: null,
  },
  {
    id: 'audit-log',
    title: {
      en: 'Audit log',
      fr: 'Journal d’audit',
    },
    body: {
      en: 'The audit log (/settings/audit-log) traces sensitive actions in the organization: logins and logouts, boat creation, update and deletion, member additions, removals and role changes, invitations sent, cancelled and accepted, and maintenance task creation, completion and deletion. Each entry records who did what and when, with filters by user, action and date range. Retention depends on the plan: no audit log on Starter, 90 days on Pro, unlimited on Enterprise.',
      fr: 'Le journal d’audit (/settings/audit-log) trace les actions sensibles de l’organisation : connexions et déconnexions, création, modification et suppression de bateaux, ajouts, retraits et changements de rôle des membres, invitations envoyées, annulées et acceptées, et création, clôture et suppression de tâches de maintenance. Chaque entrée enregistre qui a fait quoi et quand, avec filtres par utilisateur, action et plage de dates. La rétention dépend du plan : pas de journal sur Starter, 90 jours sur Pro, illimitée sur Entreprise.',
    },
    keywords: [
      'audit',
      'journal d audit',
      'audit log',
      'trace',
      'historique actions',
      'securite',
      'security',
      'retention',
      'connexions',
      'logs',
    ],
    navTarget: null,
  },
  {
    id: 'white-label',
    title: {
      en: 'White-label branding',
      fr: 'Marque blanche (branding)',
    },
    body: {
      en: 'On the Enterprise plan, the Branding settings (/settings/branding) let admins white-label FleetAi with their own identity: upload a logo, set primary and secondary colors, and define a custom application name. The branding applies to the interface, to transactional emails and to generated documents — quote and invoice PDFs carry your logo and colors instead of the default FleetAi branding. Useful for fleet managers and charter companies who present the tool to their own clients and owners.',
      fr: 'Sur le plan Entreprise, les réglages Branding (/settings/branding) permettent aux admins de mettre FleetAi à leurs couleurs : téléversement d’un logo, couleurs primaire et secondaire, et nom d’application personnalisé. Le branding s’applique à l’interface, aux emails transactionnels et aux documents générés — les PDF de devis et factures portent votre logo et vos couleurs à la place de la marque FleetAi par défaut. Utile aux gestionnaires de flotte et loueurs qui présentent l’outil à leurs propres clients et propriétaires.',
    },
    keywords: [
      'marque blanche',
      'white label',
      'branding',
      'logo',
      'couleurs',
      'colors',
      'personnalisation',
      'identite',
      'nom application',
      'entreprise',
    ],
    navTarget: null,
    planFlag: 'canWhiteLabel',
  },
  {
    id: 'assistant-actions',
    title: {
      en: 'Copilot actions: everything is confirmed by you',
      fr: 'Actions du copilote : tout est confirmé par vous',
    },
    body: {
      en: 'The FleetAi copilot can propose actions on your data: schedule a maintenance task, add engine hours, open or close a logbook trip, record a refueling, report an incident, create a reservation or a client record, update a part stock. It never writes anything by itself: each proposal appears as a card in the chat with a summary, and nothing happens until you click Confirm — Dismiss cancels it. Your role and your plan gate each action (a mechanic cannot create a client, reservations require the charter module), and every confirmed action is recorded in the organization audit log, exactly like a manual change.',
      fr: 'Le copilote FleetAi peut proposer des actions sur vos données : planifier une tâche de maintenance, ajouter des heures moteur, ouvrir ou clôturer une sortie au journal de bord, enregistrer un plein, déclarer un incident, créer une réservation ou une fiche client, mettre à jour un stock de pièce. Il n’écrit jamais rien lui-même : chaque proposition apparaît en carte dans le fil avec son résumé, et rien n’est exécuté avant votre clic sur Confirmer — Refuser l’annule. Votre rôle et votre plan conditionnent chaque action (un mécanicien ne crée pas de client, les réservations exigent le module Location), et toute action confirmée est journalisée dans le journal d’activité, comme une modification manuelle.',
    },
    keywords: [
      'copilote',
      'copilot',
      'assistant',
      'action',
      'actions',
      'confirmer',
      'confirm',
      'proposition',
      'proposal',
      'securite',
      'safety',
      'ecrire',
      'write',
      'agent',
    ],
    navTarget: null,
  },
  {
    id: 'assistant-context',
    title: {
      en: 'Copilot context: current page and starter suggestions',
      fr: 'Contexte du copilote : page courante et suggestions',
    },
    body: {
      en: 'The FleetAi copilot knows which page you are writing from: on a boat page, “this boat” or “here” refer to it without naming it. When you open the panel on an empty conversation, it offers starter suggestions built from your fleet state (overdue tasks, upcoming dues) and from the current page — one click sends the question. Behind the scenes it also loads domain playbooks (maintenance, navigation and fuel, charter, Division 240 safety, ports, plans) matched to your question, so answers follow the conventions of each domain. None of this context is stored: it is rebuilt at every message.',
      fr: 'Le copilote FleetAi sait depuis quelle page vous écrivez : sur la fiche d’un bateau, « ce bateau » ou « ici » s’y réfèrent sans le nommer. À l’ouverture du panneau sur une conversation vide, il propose des suggestions de démarrage construites depuis l’état de votre flotte (tâches en retard, échéances proches) et la page courante — un clic envoie la question. En coulisses, il charge aussi des guides par domaine (maintenance, navigation et carburant, location, sécurité Division 240, ports, plans) selon votre question, pour des réponses conformes aux conventions de chaque domaine. Rien de ce contexte n’est stocké : il est reconstruit à chaque message.',
    },
    keywords: [
      'copilote',
      'copilot',
      'assistant',
      'contexte',
      'context',
      'page',
      'suggestion',
      'suggestions',
      'starter',
      'playbook',
      'guide',
      'demarrage',
    ],
    navTarget: null,
  },
]
